import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import ExcelJS from 'exceljs';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/common/prisma.service';

const runDatabaseTests = process.env.RUN_DB_INTEGRATION === '1';

(runDatabaseTests ? describe : describe.skip)('Group reservations PostgreSQL correctness', () => {
  let app: INestApplication; let prisma: PrismaService; let hotelId: string; let roomTypeId: string; let ratePlanId: string; let ratePlanId2: string; let adminEmail: string; let token: string; let groupId = ''; const groupIds: string[] = []; const reservationIds: string[] = [];
  const checkIn = '2026-12-10'; const checkOut = '2026-12-11'; const date = new Date(`${checkIn}T00:00:00.000Z`); const multiCheckIn = '2026-12-12'; const multiCheckOut = '2026-12-15'; const multiDates = ['2026-12-12', '2026-12-13', '2026-12-14'];
  let inventoryBefore: any; let rateBefore: any; const multiInventoryBefore: any[] = []; const multiRateBefore: any[] = [];

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile(); app = moduleRef.createNestApplication(); app.setGlobalPrefix(process.env.API_PREFIX ?? 'api/v1'); app.useGlobalPipes(new ValidationPipe({ transform: true, whitelist: true, forbidNonWhitelisted: true })); await app.init(); prisma = app.get(PrismaService);
    const hotel = await prisma.hotel.findFirstOrThrow({ where: { active: true }, select: { id: true } }); const room = await prisma.roomType.findFirstOrThrow({ where: { hotelId: hotel.id, active: true }, select: { id: true } }); const plan = await prisma.ratePlan.findFirstOrThrow({ where: { roomTypeId: room.id, active: true }, select: { id: true } }); const admin = await prisma.user.findFirstOrThrow({ where: { email: process.env.E2E_ADMIN_EMAIL ?? 'admin@rainwood.demo', active: true }, select: { id: true, email: true } });
    const secondPlan = await prisma.ratePlan.findFirstOrThrow({ where: { roomTypeId: room.id, active: true, id: { not: plan.id } }, select: { id: true } }); hotelId = hotel.id; roomTypeId = room.id; ratePlanId = plan.id; ratePlanId2 = secondPlan.id; adminEmail = admin.email; inventoryBefore = await prisma.inventoryDay.findUnique({ where: { roomTypeId_date: { roomTypeId, date } } }); rateBefore = await prisma.rateDay.findUnique({ where: { ratePlanId_date: { ratePlanId, date } } });
    await prisma.inventoryDay.upsert({ where: { roomTypeId_date: { roomTypeId, date } }, create: { roomTypeId, date, available: 20, held: 0, sold: 0, groupBlocked: 0 }, update: { available: 20, held: 0, sold: 0, groupBlocked: 0, stopSell: false } });
    await prisma.rateDay.upsert({ where: { ratePlanId_date: { ratePlanId, date } }, create: { ratePlanId, date, amount: 5000, taxAmount: 0 }, update: { amount: 5000, taxAmount: 0, cta: false, ctd: false, minLos: 1 } });
    for (const value of multiDates) { const multiDate = new Date(`${value}T00:00:00.000Z`); multiInventoryBefore.push(await prisma.inventoryDay.findUnique({ where: { roomTypeId_date: { roomTypeId, date: multiDate } } })); multiRateBefore.push(await prisma.rateDay.findUnique({ where: { ratePlanId_date: { ratePlanId, date: multiDate } } })); await prisma.inventoryDay.upsert({ where: { roomTypeId_date: { roomTypeId, date: multiDate } }, create: { roomTypeId, date: multiDate, available: 20, held: 0, sold: 0, groupBlocked: 0 }, update: { available: 20, held: 0, sold: 0, groupBlocked: 0, stopSell: false } }); await prisma.rateDay.upsert({ where: { ratePlanId_date: { ratePlanId, date: multiDate } }, create: { ratePlanId, date: multiDate, amount: 5000, taxAmount: 0 }, update: { amount: 5000, taxAmount: 0, cta: false, ctd: false, minLos: 1 } }); }
    const login = await request(app.getHttpServer()).post('/api/v1/auth/login').send({ email: adminEmail, password: process.env.E2E_ADMIN_PASSWORD }).expect(201); token = login.body.accessToken;
  });

  afterAll(async () => { if (prisma) { if (reservationIds.length) await prisma.reservation.deleteMany({ where: { id: { in: reservationIds } } }); if (groupIds.length) await prisma.groupReservation.deleteMany({ where: { id: { in: groupIds } } }); else if (groupId) await prisma.groupReservation.delete({ where: { id: groupId } }).catch(() => undefined); if (inventoryBefore) await prisma.inventoryDay.update({ where: { id: inventoryBefore.id }, data: { available: inventoryBefore.available, held: inventoryBefore.held, sold: inventoryBefore.sold, groupBlocked: inventoryBefore.groupBlocked, stopSell: inventoryBefore.stopSell } }); else await prisma.inventoryDay.delete({ where: { roomTypeId_date: { roomTypeId, date } } }).catch(() => undefined); if (rateBefore) await prisma.rateDay.update({ where: { id: rateBefore.id }, data: rateBefore }); else await prisma.rateDay.delete({ where: { ratePlanId_date: { ratePlanId, date } } }).catch(() => undefined); for (let index = 0; index < multiDates.length; index += 1) { const multiDate = new Date(`${multiDates[index]}T00:00:00.000Z`); if (multiInventoryBefore[index]) await prisma.inventoryDay.update({ where: { id: multiInventoryBefore[index].id }, data: { available: multiInventoryBefore[index].available, held: multiInventoryBefore[index].held, sold: multiInventoryBefore[index].sold, groupBlocked: multiInventoryBefore[index].groupBlocked, stopSell: multiInventoryBefore[index].stopSell } }); else await prisma.inventoryDay.delete({ where: { roomTypeId_date: { roomTypeId, date: multiDate } } }).catch(() => undefined); if (multiRateBefore[index]) await prisma.rateDay.update({ where: { id: multiRateBefore[index].id }, data: multiRateBefore[index] }); else await prisma.rateDay.delete({ where: { ratePlanId_date: { ratePlanId, date: multiDate } } }).catch(() => undefined); } await prisma.$disconnect(); } await app?.close(); });

  async function availableRooms() { const response = await request(app.getHttpServer()).get('/api/v1/availability/search').set('Authorization', `Bearer ${token}`).query({ hotelId, checkIn, checkOut, rooms: 1, adults: 1, children: 0 }).expect(200); return response.body.find((item: any) => item.roomTypeId === roomTypeId).availableRooms; }

  it('keeps confirmed blocks, pickup, and release inventory balanced', async () => {
    expect(await availableRooms()).toBe(20);
    const created = await request(app.getHttpServer()).post('/api/v1/groups').set('Authorization', `Bearer ${token}`).send({ hotelId, groupName: 'Summit Operations Group', groupType: 'CORPORATE', arrivalDate: checkIn, departureDate: checkOut, primaryContactName: 'Demo Contact', primaryContactMobile: '9000000000' }); if (created.status !== 201) throw new Error(JSON.stringify(created.body)); groupId = created.body.id; groupIds.push(groupId);
    await request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/blocks`).set('Authorization', `Bearer ${token}`).send({ roomTypeId, ratePlanId, nights: [{ date: checkIn, roomsBlocked: 10 }] }).expect(201);
    await request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/confirm`).set('Authorization', `Bearer ${token}`).expect(201);
    expect(await availableRooms()).toBe(10);
    const mixedWorkbook = new ExcelJS.Workbook(); const mixedSheet = mixedWorkbook.addWorksheet('Rooming List'); mixedSheet.addRow(['Guest Name', 'Room Type', 'Check In', 'Check Out', 'Adults', 'Children']); mixedSheet.addRow(['Imported Guest', roomTypeId, checkIn, checkOut, 1, 0]); mixedSheet.addRow(['Invalid Guest', 'missing-room', checkIn, checkOut, 1, 0]);
    const preview = await request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/rooming-list/import`).set('Authorization', `Bearer ${token}`).field('commit', 'false').attach('file', Buffer.from(await mixedWorkbook.xlsx.writeBuffer()), 'rooming-list.xlsx').expect(201); expect(preview.body.rowsRead).toBe(2); expect(preview.body.rowsValid).toBe(1); expect(preview.body.rowsInvalid).toBe(1); expect(preview.body.committed).toBe(false);
    const validWorkbook = new ExcelJS.Workbook(); const validSheet = validWorkbook.addWorksheet('Rooming List'); validSheet.addRow(['Guest Name', 'Room Type', 'Check In', 'Check Out', 'Adults', 'Children']); validSheet.addRow(['Imported Guest', roomTypeId, checkIn, checkOut, 1, 0]);
    const imported = await request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/rooming-list/import`).set('Authorization', `Bearer ${token}`).field('commit', 'true').attach('file', Buffer.from(await validWorkbook.xlsx.writeBuffer()), 'rooming-list.xlsx').expect(201); expect(imported.body.rowsImported).toBe(1); const importedEntryId = imported.body.group.roomingList.find((entry: any) => entry.guestName === 'Imported Guest').id;
    const duplicatePreview = await request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/rooming-list/import`).set('Authorization', `Bearer ${token}`).field('commit', 'false').attach('file', Buffer.from(await validWorkbook.xlsx.writeBuffer()), 'rooming-list.xlsx').expect(201); expect(duplicatePreview.body.rowsValid).toBe(0); expect(duplicatePreview.body.rowsInvalid).toBe(1);
    const entries = await Promise.all(Array.from({ length: 4 }, (_, index) => request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/rooming-list`).set('Authorization', `Bearer ${token}`).send({ guestName: `Demo Guest ${index + 1}`, roomTypeId, checkIn, checkOut, adults: 1, children: 0 }).expect(201)));
    for (const response of entries) { const pickup = await request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/rooming-list/${response.body.id}/pickup`).set('Authorization', `Bearer ${token}`).send({ idempotencyKey: `group-pickup-${response.body.id}` }).expect(201); reservationIds.push(pickup.body.id); }
    const importedPickup = await request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/rooming-list/${importedEntryId}/pickup`).set('Authorization', `Bearer ${token}`).send({ idempotencyKey: `group-pickup-${importedEntryId}` }).expect(201); reservationIds.push(importedPickup.body.id);
    const retry = await Promise.all([request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/rooming-list/${importedEntryId}/pickup`).set('Authorization', `Bearer ${token}`).send({ idempotencyKey: 'same-entry-concurrent-1' }), request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/rooming-list/${importedEntryId}/pickup`).set('Authorization', `Bearer ${token}`).send({ idempotencyKey: 'same-entry-concurrent-2' })]); expect(retry[0].status).toBe(201); expect(retry[1].status).toBe(201); expect(retry[0].body.id).toBe(importedPickup.body.id); expect(retry[1].body.id).toBe(importedPickup.body.id);
    const bulkEntries = await Promise.all([1, 2].map((index) => request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/rooming-list`).set('Authorization', `Bearer ${token}`).send({ guestName: `Bulk Guest ${index}`, roomTypeId, checkIn, checkOut, adults: 1, children: 0 }).expect(201)));
    const bulk = await request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/rooming-list/create-reservations`).set('Authorization', `Bearer ${token}`).send({ entryIds: bulkEntries.map((entry) => entry.body.id) }).expect(201); expect(bulk.body.summary.created).toBe(2); bulk.body.results.forEach((item: any) => reservationIds.push(item.reservationId));
    const detail = await request(app.getHttpServer()).get(`/api/v1/groups/${groupId}`).set('Authorization', `Bearer ${token}`).expect(200); expect(detail.body.summary.remaining).toBe(3); expect(await availableRooms()).toBe(10);
    const released = await request(app.getHttpServer()).post(`/api/v1/groups/${groupId}/release`).set('Authorization', `Bearer ${token}`).expect(201); expect(released.body.summary.remaining).toBe(0); expect(await availableRooms()).toBe(13);
    const overcommitGroup = await request(app.getHttpServer()).post('/api/v1/groups').set('Authorization', `Bearer ${token}`).send({ hotelId, groupName: 'Combined Inventory Review', groupType: 'CONFERENCE', arrivalDate: checkIn, departureDate: checkOut, primaryContactName: 'Review Contact', primaryContactMobile: '9000000001' }).expect(201); groupIds.push(overcommitGroup.body.id);
    await request(app.getHttpServer()).post(`/api/v1/groups/${overcommitGroup.body.id}/blocks`).set('Authorization', `Bearer ${token}`).send({ roomTypeId, ratePlanId, nights: [{ date: checkIn, roomsBlocked: 8 }] }).expect(201);
    await request(app.getHttpServer()).post(`/api/v1/groups/${overcommitGroup.body.id}/blocks`).set('Authorization', `Bearer ${token}`).send({ roomTypeId, ratePlanId, nights: [{ date: checkIn, roomsBlocked: 8 }] }).expect(201);
    await request(app.getHttpServer()).post(`/api/v1/groups/${overcommitGroup.body.id}/confirm`).set('Authorization', `Bearer ${token}`).expect(409);
    const afterFailedConfirm = await prisma.inventoryDay.findUniqueOrThrow({ where: { roomTypeId_date: { roomTypeId, date } } }); expect(afterFailedConfirm.groupBlocked).toBe(0);

    const multiGroup = await request(app.getHttpServer()).post('/api/v1/groups').set('Authorization', `Bearer ${token}`).send({ hotelId, groupName: 'Three Night Allocation Review', groupType: 'TOUR', arrivalDate: multiCheckIn, departureDate: multiCheckOut, primaryContactName: 'Multi Night Contact', primaryContactMobile: '9000000010' }).expect(201); groupIds.push(multiGroup.body.id);
    for (const value of multiDates) await request(app.getHttpServer()).post(`/api/v1/groups/${multiGroup.body.id}/blocks`).set('Authorization', `Bearer ${token}`).send({ roomTypeId, ratePlanId, nights: [{ date: value, roomsBlocked: 1 }] }).expect(201);
    await request(app.getHttpServer()).post(`/api/v1/groups/${multiGroup.body.id}/confirm`).set('Authorization', `Bearer ${token}`).expect(201);
    const multiEntry = await request(app.getHttpServer()).post(`/api/v1/groups/${multiGroup.body.id}/rooming-list`).set('Authorization', `Bearer ${token}`).send({ guestName: 'Three Night Guest', roomTypeId, checkIn: multiCheckIn, checkOut: multiCheckOut, adults: 1, children: 0 }).expect(201);
    const multiPickup = await request(app.getHttpServer()).post(`/api/v1/groups/${multiGroup.body.id}/rooming-list/${multiEntry.body.id}/pickup`).set('Authorization', `Bearer ${token}`).send({ idempotencyKey: `multi-night-${multiEntry.body.id}` }).expect(201); reservationIds.push(multiPickup.body.id);
    const multiNights = await prisma.groupRoomBlockNight.findMany({ where: { groupRoomBlock: { groupReservationId: multiGroup.body.id } }, orderBy: { date: 'asc' } }); expect(multiNights).toHaveLength(3); expect(multiNights.every((night) => night.roomsBlocked === 1 && night.roomsPickedUp === 1 && night.roomsReleased === 0)).toBe(true);

    const concurrentGroup = await request(app.getHttpServer()).post('/api/v1/groups').set('Authorization', `Bearer ${token}`).send({ hotelId, groupName: 'Last Room Concurrency Review', groupType: 'CONFERENCE', arrivalDate: checkIn, departureDate: checkOut, primaryContactName: 'Concurrency Contact', primaryContactMobile: '9000000011' }).expect(201); groupIds.push(concurrentGroup.body.id);
    await request(app.getHttpServer()).post(`/api/v1/groups/${concurrentGroup.body.id}/blocks`).set('Authorization', `Bearer ${token}`).send({ roomTypeId, ratePlanId, nights: [{ date: checkIn, roomsBlocked: 1 }] }).expect(201); await request(app.getHttpServer()).post(`/api/v1/groups/${concurrentGroup.body.id}/confirm`).set('Authorization', `Bearer ${token}`).expect(201);
    const concurrentEntries = await prisma.groupRoomingListEntry.createMany({ data: [1, 2].map((index) => ({ groupReservationId: concurrentGroup.body.id, roomTypeId, guestName: `Concurrent Guest ${index}`, checkIn: date, checkOut: new Date(`${checkOut}T00:00:00.000Z`), adults: 1, children: 0, status: 'READY' })) }); expect(concurrentEntries.count).toBe(2);
    const concurrentRows = await prisma.groupRoomingListEntry.findMany({ where: { groupReservationId: concurrentGroup.body.id }, orderBy: { createdAt: 'asc' }, select: { id: true } });
    const concurrentPickups = await Promise.all(concurrentRows.map((entry) => request(app.getHttpServer()).post(`/api/v1/groups/${concurrentGroup.body.id}/rooming-list/${entry.id}/pickup`).set('Authorization', `Bearer ${token}`).send({ idempotencyKey: `different-entry-${entry.id}` }))); expect(concurrentPickups.map((response) => response.status).sort()).toEqual([201, 409]); const concurrentSuccess = concurrentPickups.find((response) => response.status === 201)!; reservationIds.push(concurrentSuccess.body.id); const concurrentNight = await prisma.groupRoomBlockNight.findFirstOrThrow({ where: { groupRoomBlock: { groupReservationId: concurrentGroup.body.id } } }); expect(concurrentNight.roomsPickedUp).toBe(1);
    await request(app.getHttpServer()).post(`/api/v1/reservations/${concurrentSuccess.body.reference}/no-show`).set('Authorization', `Bearer ${token}`).send({ reason: 'Synthetic operational no-show.' }).expect(201); const noShowGroup = await request(app.getHttpServer()).get(`/api/v1/groups/${concurrentGroup.body.id}`).set('Authorization', `Bearer ${token}`).expect(200); expect(noShowGroup.body.status).toBe('COMPLETED');

    const editGroup = await request(app.getHttpServer()).post('/api/v1/groups').set('Authorization', `Bearer ${token}`).send({ hotelId, groupName: 'Block History Review', groupType: 'CORPORATE', arrivalDate: multiCheckIn, departureDate: '2026-12-14', primaryContactName: 'Edit Contact', primaryContactMobile: '9000000012' }).expect(201); groupIds.push(editGroup.body.id);
    const editBlock = await request(app.getHttpServer()).post(`/api/v1/groups/${editGroup.body.id}/blocks`).set('Authorization', `Bearer ${token}`).send({ roomTypeId, ratePlanId, nights: [{ date: multiDates[0], roomsBlocked: 4 }, { date: multiDates[1], roomsBlocked: 4 }] }).expect(201); const editBlockId = editBlock.body.roomBlocks[0]?.id ?? editBlock.body.id;
    const editBlockDetail = await request(app.getHttpServer()).get(`/api/v1/groups/${editGroup.body.id}`).set('Authorization', `Bearer ${token}`).expect(200); const actualEditBlockId = editBlockDetail.body.roomBlocks[0].id;
    await request(app.getHttpServer()).post(`/api/v1/groups/${editGroup.body.id}/confirm`).set('Authorization', `Bearer ${token}`).expect(201);
    const editEntry = await request(app.getHttpServer()).post(`/api/v1/groups/${editGroup.body.id}/rooming-list`).set('Authorization', `Bearer ${token}`).send({ guestName: 'History Guest', roomTypeId, checkIn: multiDates[0], checkOut: multiDates[1], adults: 1, children: 0 }).expect(201); const editReservation = await request(app.getHttpServer()).post(`/api/v1/groups/${editGroup.body.id}/rooming-list/${editEntry.body.id}/pickup`).set('Authorization', `Bearer ${token}`).send({ idempotencyKey: `history-${editEntry.body.id}` }).expect(201); reservationIds.push(editReservation.body.id);
    await request(app.getHttpServer()).patch(`/api/v1/groups/${editGroup.body.id}/blocks/${actualEditBlockId}`).set('Authorization', `Bearer ${token}`).send({ nights: [{ date: multiDates[1], roomsBlocked: 4 }] }).expect(409);
    const beforeHistory = await prisma.groupRoomBlockNight.findMany({ where: { groupRoomBlockId: actualEditBlockId }, orderBy: { date: 'asc' } }); expect(beforeHistory).toHaveLength(2);
    await request(app.getHttpServer()).patch(`/api/v1/groups/${editGroup.body.id}/blocks/${actualEditBlockId}`).set('Authorization', `Bearer ${token}`).send({ nights: [{ date: multiDates[0], roomsBlocked: 3 }] }).expect(200); const afterHistory = await prisma.groupRoomBlockNight.findFirstOrThrow({ where: { groupRoomBlockId: actualEditBlockId } }); expect(afterHistory.id).toBe(beforeHistory[0].id); expect(afterHistory.roomsPickedUp).toBe(1); expect(afterHistory.roomsBlocked).toBe(3);
  });

  it('enforces the feature-local Accounts and Viewer read scope with real actor shapes', async () => {
    const users = await prisma.user.findMany({ where: { email: { in: ['accounts@rainwood.demo', 'viewer@rainwood.demo', 'reservation@rainwood.demo', 'hotel.admin@rainwood.demo'] } }, select: { email: true, role: true, staffHotelId: true } });
    expect(users.find((user) => user.email === 'accounts@rainwood.demo')).toMatchObject({ role: 'ACCOUNTS', staffHotelId: null });
    expect(users.find((user) => user.email === 'viewer@rainwood.demo')).toMatchObject({ role: 'VIEWER', staffHotelId: null });
    expect(users.find((user) => user.email === 'reservation@rainwood.demo')).toMatchObject({ role: 'RESERVATION', staffHotelId: hotelId });
    expect(users.find((user) => user.email === 'hotel.admin@rainwood.demo')).toMatchObject({ role: 'ADMIN', staffHotelId: hotelId });

    async function actorToken(email: string) {
      const response = await request(app.getHttpServer()).post('/api/v1/auth/login').send({ email, password: process.env.E2E_ADMIN_PASSWORD }).expect(201);
      return response.body.accessToken as string;
    }
    for (const email of ['accounts@rainwood.demo', 'viewer@rainwood.demo']) {
      const actor = await actorToken(email);
      const list = await request(app.getHttpServer()).get('/api/v1/groups').set('Authorization', `Bearer ${actor}`).query({ hotelId }).expect(200);
      expect(list.body.items.some((item: any) => item.id === groupId)).toBe(true);
      await request(app.getHttpServer()).get(`/api/v1/groups/${groupId}`).set('Authorization', `Bearer ${actor}`).query({ hotelId }).expect(200);
      await request(app.getHttpServer()).post('/api/v1/groups').set('Authorization', `Bearer ${actor}`).send({ hotelId, groupName: 'Read Only Attempt', groupType: 'CORPORATE', arrivalDate: checkIn, departureDate: checkOut, primaryContactName: 'Read Only', primaryContactMobile: '9000000099' }).expect(403);
    }
    const otherHotelId = 'hotel-b-not-assigned';
    for (const email of ['hotel.admin@rainwood.demo', 'reservation@rainwood.demo']) {
      const actor = await actorToken(email);
      await request(app.getHttpServer()).get('/api/v1/groups').set('Authorization', `Bearer ${actor}`).query({ hotelId: otherHotelId }).expect(403);
      await request(app.getHttpServer()).get(`/api/v1/groups/${groupId}`).set('Authorization', `Bearer ${actor}`).query({ hotelId: otherHotelId }).expect(403);
    }
  });

  it('accepts metadata edits and checkout-equals-departure while enforcing date and rate-plan safeguards', async () => {
    const dates = ['2026-12-20', '2026-12-21', '2026-12-22', '2026-12-24', '2026-12-25'];
    const snapshots = new Map<string, any>();
    for (const value of dates) {
      const currentDate = new Date(`${value}T00:00:00.000Z`);
      snapshots.set(value, await prisma.inventoryDay.findUnique({ where: { roomTypeId_date: { roomTypeId, date: currentDate } } }));
      await prisma.inventoryDay.upsert({ where: { roomTypeId_date: { roomTypeId, date: currentDate } }, create: { roomTypeId, date: currentDate, available: 20, held: 0, sold: 0, groupBlocked: 0 }, update: { available: 20, held: 0, sold: 0, groupBlocked: 0, stopSell: false } });
      for (const plan of [ratePlanId, ratePlanId2]) await prisma.rateDay.upsert({ where: { ratePlanId_date: { ratePlanId: plan, date: currentDate } }, create: { ratePlanId: plan, date: currentDate, amount: 5000, taxAmount: 0 }, update: { amount: 5000, taxAmount: 0, cta: false, ctd: false, minLos: 1 } });
    }
    const cleanupInventory = async () => { for (const value of dates) { const currentDate = new Date(`${value}T00:00:00.000Z`); const snapshot = snapshots.get(value); if (snapshot) await prisma.inventoryDay.update({ where: { id: snapshot.id }, data: { available: snapshot.available, held: snapshot.held, sold: snapshot.sold, groupBlocked: snapshot.groupBlocked, stopSell: snapshot.stopSell } }); else await prisma.inventoryDay.delete({ where: { roomTypeId_date: { roomTypeId, date: currentDate } } }).catch(() => undefined); } };

    const mixed = await request(app.getHttpServer()).post('/api/v1/groups').set('Authorization', `Bearer ${token}`).send({ hotelId, groupName: 'Mixed Rate Plan Safeguard', groupType: 'TOUR', arrivalDate: '2026-12-20', departureDate: '2026-12-23', primaryContactName: 'Synthetic Contact', primaryContactMobile: '9000000020' }).expect(201); groupIds.push(mixed.body.id);
    await request(app.getHttpServer()).post(`/api/v1/groups/${mixed.body.id}/blocks`).set('Authorization', `Bearer ${token}`).send({ roomTypeId, ratePlanId, nights: [{ date: '2026-12-20', roomsBlocked: 1 }] }).expect(201);
    await request(app.getHttpServer()).post(`/api/v1/groups/${mixed.body.id}/blocks`).set('Authorization', `Bearer ${token}`).send({ roomTypeId, ratePlanId: ratePlanId2, nights: [{ date: '2026-12-21', roomsBlocked: 1 }] }).expect(201);
    await request(app.getHttpServer()).post(`/api/v1/groups/${mixed.body.id}/blocks`).set('Authorization', `Bearer ${token}`).send({ roomTypeId, nights: [{ date: '2026-12-22', roomsBlocked: 1 }] }).expect(201);
    await request(app.getHttpServer()).post(`/api/v1/groups/${mixed.body.id}/confirm`).set('Authorization', `Bearer ${token}`).expect(201);
    const mixedEntry = await request(app.getHttpServer()).post(`/api/v1/groups/${mixed.body.id}/rooming-list`).set('Authorization', `Bearer ${token}`).send({ guestName: 'Mixed Plan Guest', roomTypeId, checkIn: '2026-12-20', checkOut: '2026-12-23', adults: 1, children: 0 }).expect(201);
    await request(app.getHttpServer()).post(`/api/v1/groups/${mixed.body.id}/rooming-list/${mixedEntry.body.id}/pickup`).set('Authorization', `Bearer ${token}`).send({ idempotencyKey: `mixed-${mixedEntry.body.id}` }).expect(409).expect((response) => expect(response.body.message).toContain('different rate plans'));

    const editable = await request(app.getHttpServer()).post('/api/v1/groups').set('Authorization', `Bearer ${token}`).send({ hotelId, groupName: 'Metadata Edit Safeguard', groupType: 'CORPORATE', arrivalDate: '2026-12-20', departureDate: '2026-12-23', primaryContactName: 'Initial Contact', primaryContactMobile: '9000000021' }).expect(201); groupIds.push(editable.body.id);
    const block = { roomTypeId, ratePlanId, nights: [{ date: '2026-12-20', roomsBlocked: 1 }, { date: '2026-12-21', roomsBlocked: 1 }, { date: '2026-12-22', roomsBlocked: 1 }] };
    await request(app.getHttpServer()).post(`/api/v1/groups/${editable.body.id}/blocks`).set('Authorization', `Bearer ${token}`).send(block).expect(201);
    await request(app.getHttpServer()).post(`/api/v1/groups/${editable.body.id}/confirm`).set('Authorization', `Bearer ${token}`).expect(201);
    const entry = await request(app.getHttpServer()).post(`/api/v1/groups/${editable.body.id}/rooming-list`).set('Authorization', `Bearer ${token}`).send({ guestName: 'Metadata Guest', roomTypeId, checkIn: '2026-12-20', checkOut: '2026-12-23', adults: 1, children: 0 }).expect(201);
    await request(app.getHttpServer()).patch(`/api/v1/groups/${editable.body.id}`).set('Authorization', `Bearer ${token}`).send({ primaryContactName: 'Updated Before Pickup', notes: 'Updated before pickup' }).expect(200);
    const picked = await request(app.getHttpServer()).post(`/api/v1/groups/${editable.body.id}/rooming-list/${entry.body.id}/pickup`).set('Authorization', `Bearer ${token}`).send({ idempotencyKey: `metadata-${entry.body.id}` }).expect(201); reservationIds.push(picked.body.id);
    await request(app.getHttpServer()).patch(`/api/v1/groups/${editable.body.id}`).set('Authorization', `Bearer ${token}`).send({ primaryContactName: 'Updated After Pickup', notes: 'Updated after pickup' }).expect(200);
    await request(app.getHttpServer()).patch(`/api/v1/groups/${editable.body.id}`).set('Authorization', `Bearer ${token}`).send({ departureDate: '2026-12-22' }).expect(400);

    const fallback = await request(app.getHttpServer()).post('/api/v1/groups').set('Authorization', `Bearer ${token}`).send({ hotelId, groupName: 'Fallback Rate Plan', groupType: 'TOUR', arrivalDate: '2026-12-24', departureDate: '2026-12-26', primaryContactName: 'Fallback Contact', primaryContactMobile: '9000000022' }).expect(201); groupIds.push(fallback.body.id);
    await request(app.getHttpServer()).post(`/api/v1/groups/${fallback.body.id}/blocks`).set('Authorization', `Bearer ${token}`).send({ roomTypeId, nights: [{ date: '2026-12-24', roomsBlocked: 1 }, { date: '2026-12-25', roomsBlocked: 1 }] }).expect(201);
    await request(app.getHttpServer()).post(`/api/v1/groups/${fallback.body.id}/confirm`).set('Authorization', `Bearer ${token}`).expect(201);
    const fallbackEntry = await request(app.getHttpServer()).post(`/api/v1/groups/${fallback.body.id}/rooming-list`).set('Authorization', `Bearer ${token}`).send({ guestName: 'Fallback Guest', roomTypeId, checkIn: '2026-12-24', checkOut: '2026-12-26', adults: 1, children: 0 }).expect(201);
    const fallbackReservation = await request(app.getHttpServer()).post(`/api/v1/groups/${fallback.body.id}/rooming-list/${fallbackEntry.body.id}/pickup`).set('Authorization', `Bearer ${token}`).send({ idempotencyKey: `fallback-${fallbackEntry.body.id}` }).expect(201); reservationIds.push(fallbackReservation.body.id);
    await cleanupInventory();
  });
});
