import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { BanquetBEOStatus, BanquetEventStatus, BanquetFunctionStatus, Prisma, UserRole } from '@prisma/client';
import { AuditService } from '../../common/audit.service';
import { getActorScope, resolveRequestedHotel } from '../../common/role-scope';
import { hotelLocalDateTimeToUtc, getHotelOperationalDate } from '../../common/hotel-dates';
import { parseDateOnly, toDateOnly } from '../../common/dates';
import { nextDocumentNumber } from '../../common/document-sequences';
import { PrismaService } from '../../common/prisma.service';
import { BanquetCalendarQueryDto, BanquetEventCreateDto, BanquetEventListQueryDto, BanquetEventUpdateDto, BanquetFunctionCreateDto, BanquetFunctionUpdateDto, BanquetLinkOptionsQueryDto, BeoChargeLineDto, BeoRequirementDto, BeoScheduleItemDto, BeoUpdateDto, FunctionAvailabilityQueryDto, FunctionSpaceCreateDto, FunctionSpaceListQueryDto, FunctionSpaceUpdateDto } from './banquets.dto';

const WRITERS: UserRole[] = [UserRole.SUPER_ADMIN, UserRole.CORPORATE_ADMIN, UserRole.ADMIN, UserRole.RESERVATION];
const READERS: UserRole[] = [...WRITERS, UserRole.ACCOUNTS, UserRole.VIEWER];
const ACTIVE_FUNCTION_STATUSES = { not: BanquetFunctionStatus.CANCELLED };

function clean(value?: string | null) { return value?.trim() || null; }
function money(value: number) { return Math.round(value * 100) / 100; }
function localDate(value: string) { return parseDateOnly(value, 'function date'); }
function capacityFor(space: any, setup: string) { return ({ THEATRE: space.capacityTheatre, CLASSROOM: space.capacityClassroom, BOARDROOM: space.capacityBoardroom, U_SHAPE: space.capacityUShape, BANQUET: space.capacityBanquet, RECEPTION: space.capacityReception } as Record<string, number | null | undefined>)[setup] ?? null; }

@Injectable()
export class BanquetsService {
  constructor(private readonly p: PrismaService, private readonly audit: AuditService) {}

  private async scope(userId: string, requestedHotelId?: string, write = false) {
    const scope = await getActorScope(this.p, userId);
    if (!(write ? WRITERS : READERS).includes(scope.role)) throw new ForbiddenException('Banquet access is not available to this account.');
    if (write && !WRITERS.includes(scope.role)) throw new ForbiddenException('This role has read-only banquet access.');
    if (!write && (scope.role === UserRole.ACCOUNTS || scope.role === UserRole.VIEWER)) return { ...scope, isGlobal: true, hotelId: resolveRequestedHotel({ ...scope, isGlobal: true }, requestedHotelId) };
    return { ...scope, hotelId: resolveRequestedHotel(scope, requestedHotelId) };
  }

  private async hotelFor(hotelId: string) {
    const hotel = await this.p.hotel.findUnique({ where: { id: hotelId }, select: { id: true, name: true, code: true, active: true, timezoneName: true } });
    if (!hotel?.active) throw new NotFoundException('Hotel not found.');
    return hotel;
  }

  private async assertHotel(userId: string, hotelId: string, write = false) {
    const scope = await this.scope(userId, hotelId, write);
    if (scope.hotelId && scope.hotelId !== hotelId) throw new ForbiddenException('You cannot access another hotel.');
    return this.hotelFor(hotelId);
  }

  async spaces(userId: string, query: FunctionSpaceListQueryDto) {
    const scope = await this.scope(userId, query.hotelId);
    const rows = await this.p.functionSpace.findMany({ where: { hotelId: scope.hotelId ?? undefined, spaceType: query.spaceType, active: query.active === undefined ? undefined : Boolean(query.active), OR: query.search ? [{ name: { contains: query.search, mode: 'insensitive' } }, { code: { contains: query.search, mode: 'insensitive' } }] : undefined }, orderBy: [{ active: 'desc' }, { name: 'asc' }] });
    return rows;
  }

  async linkOptions(userId: string, query: BanquetLinkOptionsQueryDto) {
    const scope = await this.scope(userId, query.hotelId);
    const hotelId = scope.hotelId;
    if (!hotelId) throw new BadRequestException('hotelId is required for banquet link options.');
    const text = query.search?.trim();
    const [hotel, groups, corporates, inquiries, agents] = await Promise.all([
      this.hotelFor(hotelId),
      this.p.groupReservation.findMany({ where: { hotelId, ...(text ? { OR: [{ groupCode: { contains: text, mode: 'insensitive' } }, { groupName: { contains: text, mode: 'insensitive' } }] } : {}) }, orderBy: { arrivalDate: 'desc' }, take: 25, select: { id: true, groupCode: true, groupName: true, arrivalDate: true, departureDate: true, corporateId: true, agentId: true } }),
      this.p.corporateAccount.findMany({ where: { active: true, hotels: { some: { hotelId, active: true } }, ...(text ? { name: { contains: text, mode: 'insensitive' } } : {}) }, orderBy: { name: 'asc' }, take: 25, select: { id: true, name: true } }),
      this.p.bookingInquiry.findMany({ where: { hotelId, ...(text ? { OR: [{ inquiryNo: { contains: text, mode: 'insensitive' } }, { guestName: { contains: text, mode: 'insensitive' } }] } : {}) }, orderBy: { createdAt: 'desc' }, take: 25, select: { id: true, inquiryNo: true, guestName: true, checkIn: true, checkOut: true, status: true } }),
      this.p.user.findMany({ where: { active: true, role: UserRole.AGENT, assignedRatePlans: { some: { active: true, ratePlan: { active: true, roomType: { hotelId } } } }, ...(text ? { OR: [{ name: { contains: text, mode: 'insensitive' } }, { email: { contains: text, mode: 'insensitive' } }] } : {}) }, orderBy: { name: 'asc' }, take: 25, select: { id: true, name: true, email: true } }),
    ]);
    return { hotel, groups, corporates, inquiries, agents };
  }

  async createSpace(userId: string, body: FunctionSpaceCreateDto) {
    await this.assertHotel(userId, body.hotelId, true);
    const row = await this.p.functionSpace.create({ data: { hotelId: body.hotelId, name: body.name.trim(), code: body.code.trim().toUpperCase(), spaceType: body.spaceType, floor: clean(body.floor), locationDescription: clean(body.locationDescription), areaSqFt: body.areaSqFt, capacityTheatre: body.capacityTheatre, capacityClassroom: body.capacityClassroom, capacityBoardroom: body.capacityBoardroom, capacityUShape: body.capacityUShape, capacityBanquet: body.capacityBanquet, capacityReception: body.capacityReception, active: body.active ?? true, outOfService: body.outOfService ?? false, notes: clean(body.notes) } });
    await this.audit.log({ actorUserId: userId, action: 'FUNCTION_SPACE_CREATED', entityType: 'FunctionSpace', entityId: row.id, after: { hotelId: row.hotelId, code: row.code, name: row.name } });
    return row;
  }

  async updateSpace(userId: string, id: string, body: FunctionSpaceUpdateDto) {
    const current = await this.p.functionSpace.findUnique({ where: { id }, include: { hotel: { select: { timezoneName: true } } } });
    if (!current) throw new NotFoundException('Function space not found.');
    await this.assertHotel(userId, current.hotelId, true);
    const row = await this.p.functionSpace.update({ where: { id }, data: { name: body.name?.trim(), code: body.code?.trim().toUpperCase(), spaceType: body.spaceType, floor: body.floor === undefined ? undefined : clean(body.floor), locationDescription: body.locationDescription === undefined ? undefined : clean(body.locationDescription), areaSqFt: body.areaSqFt, capacityTheatre: body.capacityTheatre, capacityClassroom: body.capacityClassroom, capacityBoardroom: body.capacityBoardroom, capacityUShape: body.capacityUShape, capacityBanquet: body.capacityBanquet, capacityReception: body.capacityReception, active: body.active, outOfService: body.outOfService, notes: body.notes === undefined ? undefined : clean(body.notes) } });
    const hotelToday = getHotelOperationalDate(current.hotel.timezoneName);
    const upcomingFunctionCount = row.outOfService ? await this.p.banquetFunction.count({ where: { functionSpaceId: id, status: ACTIVE_FUNCTION_STATUSES, functionDate: { gte: hotelToday }, banquetEvent: { status: { notIn: [BanquetEventStatus.CANCELLED, BanquetEventStatus.COMPLETED] } } } }) : 0;
    await this.audit.log({ actorUserId: userId, action: 'FUNCTION_SPACE_UPDATED', entityType: 'FunctionSpace', entityId: id, before: { active: current.active, outOfService: current.outOfService }, after: { fields: Object.keys(body), active: row.active, outOfService: row.outOfService, upcomingFunctionCount } });
    return { ...row, upcomingFunctionCount };
  }

  async list(userId: string, query: BanquetEventListQueryDto) {
    const scope = await this.scope(userId, query.hotelId);
    const page = Math.max(1, Number(query.page) || 1); const limit = Math.min(100, Math.max(1, Number(query.limit) || 25));
    const where: Prisma.BanquetEventWhereInput = { hotelId: scope.hotelId ?? undefined, status: query.status, eventType: query.eventType, corporateId: query.corporateId, groupReservationId: query.groupReservationId, startDate: query.from || query.to ? { gte: query.from ? localDate(query.from) : undefined, lte: query.to ? localDate(query.to) : undefined } : undefined, functions: query.functionSpaceId ? { some: { functionSpaceId: query.functionSpaceId } } : undefined };
    if (query.search?.trim()) { const text = query.search.trim(); where.OR = [{ eventCode: { contains: text, mode: 'insensitive' } }, { eventName: { contains: text, mode: 'insensitive' } }, { primaryContactName: { contains: text, mode: 'insensitive' } }, { primaryContactMobile: { contains: text, mode: 'insensitive' } }, { groupReservation: { groupName: { contains: text, mode: 'insensitive' } } }, { groupReservation: { groupCode: { contains: text, mode: 'insensitive' } } }, { corporate: { name: { contains: text, mode: 'insensitive' } } }]; }
    const [total, items] = await this.p.$transaction([this.p.banquetEvent.count({ where }), this.p.banquetEvent.findMany({ where, orderBy: [{ startDate: 'asc' }, { eventCode: 'asc' }], skip: (page - 1) * limit, take: limit, include: { hotel: { select: { id: true, name: true } }, groupReservation: { select: { id: true, groupCode: true, groupName: true } }, corporate: { select: { id: true, name: true } }, functions: { select: { id: true, functionName: true, functionDate: true, startTime: true, endTime: true, status: true, functionSpace: { select: { id: true, name: true } }, beo: { select: { status: true } } }, orderBy: { functionDate: 'asc' } }, _count: { select: { functions: true } } } })]);
    return { items, pagination: { page, limit, total, pages: Math.max(1, Math.ceil(total / limit)) } };
  }

  async detail(userId: string, id: string, hotelId?: string) {
    const scope = await this.scope(userId, hotelId);
    const row = await this.p.banquetEvent.findUnique({ where: { id }, include: { hotel: { select: { id: true, name: true, code: true, timezoneName: true } }, groupReservation: { select: { id: true, groupCode: true, groupName: true, primaryContactName: true } }, inquiry: { select: { id: true, inquiryNo: true, guestName: true } }, corporate: { select: { id: true, name: true } }, agent: { select: { id: true, name: true, email: true } }, functions: { orderBy: [{ functionDate: 'asc' }, { startAt: 'asc' }], include: { functionSpace: true, beo: { include: { finalizedBy: { select: { id: true, name: true } }, scheduleItems: { orderBy: [{ sortOrder: 'asc' }, { itemTime: 'asc' }] }, requirements: { orderBy: { createdAt: 'asc' } }, chargeLines: { orderBy: { createdAt: 'asc' } } } } } }, chargeLines: { where: { beoId: null }, orderBy: { createdAt: 'asc' } } } });
    if (!row || (scope.hotelId && row.hotelId !== scope.hotelId)) throw new NotFoundException('Banquet event not found.');
    const activity = await this.p.auditLog.findMany({ where: { entityType: { in: ['BanquetEvent', 'BanquetFunction', 'BanquetEventOrder', 'BanquetRequirement'] }, OR: [{ entityId: id }, { after: { path: ['eventId'], equals: id } }] }, orderBy: { createdAt: 'desc' }, take: 50, select: { id: true, action: true, entityType: true, entityId: true, after: true, createdAt: true, actor: { select: { name: true } } } });
    return { ...row, activity };
  }

  private async validateLinks(db: PrismaService | Prisma.TransactionClient, hotelId: string, links: { groupReservationId?: string | null; inquiryId?: string | null; corporateId?: string | null; agentId?: string | null }) {
    if (links.groupReservationId && !(await db.groupReservation.findFirst({ where: { id: links.groupReservationId, hotelId }, select: { id: true } }))) throw new BadRequestException('Group reservation is not available for this hotel.');
    if (links.inquiryId && !(await db.bookingInquiry.findFirst({ where: { id: links.inquiryId, hotelId }, select: { id: true } }))) throw new BadRequestException('Booking inquiry is not available for this hotel.');
    if (links.corporateId && !(await db.corporateAccount.findFirst({ where: { id: links.corporateId, active: true, hotels: { some: { hotelId, active: true } } }, select: { id: true } }))) throw new BadRequestException('Corporate account is not active or linked to this hotel.');
    if (links.agentId && !(await db.user.findFirst({ where: { id: links.agentId, role: UserRole.AGENT, active: true, assignedRatePlans: { some: { active: true, ratePlan: { active: true, roomType: { hotelId } } } } }, select: { id: true } }))) throw new BadRequestException('Agent account is not active or commercially linked to this hotel.');
  }

  private validateTransition(current: BanquetEventStatus, next?: BanquetEventStatus, reason?: string | null) {
    if (!next || next === current) return;
    const allowed: Record<BanquetEventStatus, BanquetEventStatus[]> = {
      INQUIRY: [BanquetEventStatus.TENTATIVE, BanquetEventStatus.CANCELLED],
      TENTATIVE: [BanquetEventStatus.CONFIRMED, BanquetEventStatus.CANCELLED],
      CONFIRMED: [BanquetEventStatus.IN_PROGRESS, BanquetEventStatus.CANCELLED],
      IN_PROGRESS: [BanquetEventStatus.COMPLETED, BanquetEventStatus.CANCELLED],
      COMPLETED: [],
      CANCELLED: [],
    };
    if (!allowed[current].includes(next)) throw new BadRequestException(`Event status cannot move from ${current} to ${next}.`);
    if (next === BanquetEventStatus.CANCELLED && !reason?.trim()) throw new BadRequestException('A cancellation reason is required.');
  }

  async createEvent(userId: string, body: BanquetEventCreateDto) {
    const hotel = await this.assertHotel(userId, body.hotelId, true); const start = localDate(body.startDate); const end = localDate(body.endDate); if (end < start) throw new BadRequestException('Event end date must be on or after the start date.'); if (body.guaranteedPax !== undefined && body.expectedPax !== undefined && body.guaranteedPax > body.expectedPax) throw new BadRequestException('Guaranteed PAX cannot exceed expected PAX.');
    await this.validateLinks(this.p, body.hotelId, body);
    const row = await this.p.$transaction(async (tx) => { const year = getHotelOperationalDate(hotel.timezoneName).getUTCFullYear(); await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`${body.hotelId}:BANQUET_EVENT:${year}`}, 0))`; const eventCode = await nextDocumentNumber(tx, body.hotelId, 'BANQUET_EVENT', year, `BQT-${hotel.code}`); return tx.banquetEvent.create({ data: { hotelId: body.hotelId, eventCode, eventName: body.eventName.trim(), eventType: body.eventType, status: body.status ?? BanquetEventStatus.INQUIRY, groupReservationId: body.groupReservationId || null, inquiryId: body.inquiryId || null, corporateId: body.corporateId || null, agentId: body.agentId || null, primaryContactName: body.primaryContactName.trim(), primaryContactMobile: body.primaryContactMobile.trim(), primaryContactEmail: clean(body.primaryContactEmail), startDate: start, endDate: end, expectedPax: body.expectedPax, guaranteedPax: body.guaranteedPax, notes: clean(body.notes), createdByUserId: userId } }); });
    await this.audit.log({ actorUserId: userId, action: 'BANQUET_EVENT_CREATED', entityType: 'BanquetEvent', entityId: row.id, after: { hotelId: row.hotelId, eventCode: row.eventCode, eventName: row.eventName } }); return this.detail(userId, row.id);
  }

  async updateEvent(userId: string, id: string, body: BanquetEventUpdateDto) {
    const current = await this.p.banquetEvent.findUnique({ where: { id }, include: { functions: { select: { id: true, functionDate: true, status: true } }, hotel: { select: { code: true } } } }); if (!current) throw new NotFoundException('Banquet event not found.'); await this.assertHotel(userId, current.hotelId, true); const start = body.startDate ? localDate(body.startDate) : current.startDate; const end = body.endDate ? localDate(body.endDate) : current.endDate; if (end < start) throw new BadRequestException('Event end date must be on or after the start date.'); if ((body.startDate || body.endDate) && current.functions.some((item) => item.status !== BanquetFunctionStatus.CANCELLED && (item.functionDate < start || item.functionDate > end))) throw new BadRequestException('Event dates must contain every existing non-cancelled function.');
    const links = { groupReservationId: body.groupReservationId === undefined ? current.groupReservationId : body.groupReservationId, inquiryId: body.inquiryId === undefined ? current.inquiryId : body.inquiryId, corporateId: body.corporateId === undefined ? current.corporateId : body.corporateId, agentId: body.agentId === undefined ? current.agentId : body.agentId }; await this.validateLinks(this.p, current.hotelId, links); this.validateTransition(current.status, body.status, body.reason);
    const row = await this.p.$transaction(async (tx) => { const nextStatus = body.status ?? current.status; const updated = await tx.banquetEvent.update({ where: { id }, data: { eventName: body.eventName?.trim(), eventType: body.eventType, status: nextStatus, groupReservationId: links.groupReservationId, inquiryId: links.inquiryId, corporateId: links.corporateId, agentId: links.agentId, primaryContactName: body.primaryContactName?.trim(), primaryContactMobile: body.primaryContactMobile?.trim(), primaryContactEmail: body.primaryContactEmail === undefined ? undefined : clean(body.primaryContactEmail), startDate: start, endDate: end, expectedPax: body.expectedPax, guaranteedPax: body.guaranteedPax, notes: body.notes === undefined ? undefined : clean(body.notes), cancellationReason: nextStatus === BanquetEventStatus.CANCELLED ? body.reason?.trim() ?? current.cancellationReason : undefined } }); if (nextStatus === BanquetEventStatus.CANCELLED && current.status !== BanquetEventStatus.CANCELLED) { const released = await tx.banquetFunction.updateMany({ where: { banquetEventId: id, status: { notIn: [BanquetFunctionStatus.CANCELLED, BanquetFunctionStatus.COMPLETED] } }, data: { status: BanquetFunctionStatus.CANCELLED } }); await tx.auditLog.create({ data: { actorUserId: userId, action: 'BANQUET_FUNCTIONS_RELEASED_BY_EVENT_CANCELLATION', entityType: 'BanquetEvent', entityId: id, after: { releasedCount: released.count } } }); } await tx.auditLog.create({ data: { actorUserId: userId, action: nextStatus === BanquetEventStatus.CANCELLED ? 'BANQUET_EVENT_CANCELLED' : 'BANQUET_EVENT_UPDATED', entityType: 'BanquetEvent', entityId: id, before: { status: current.status }, after: { status: nextStatus, fields: Object.keys(body) } } }); return updated; }); return this.detail(userId, row.id);
  }

  private async functionInput(userId: string, eventId: string, body: BanquetFunctionCreateDto, functionId?: string) {
    const event = await this.p.banquetEvent.findUnique({ where: { id: eventId }, include: { hotel: { select: { id: true, name: true, timezoneName: true }, }, } }); if (!event) throw new NotFoundException('Banquet event not found.'); await this.assertHotel(userId, event.hotelId, true); if (event.status === BanquetEventStatus.CANCELLED || event.status === BanquetEventStatus.COMPLETED) throw new BadRequestException(`A new function cannot be added to a ${event.status.toLowerCase()} event.`); const date = localDate(body.functionDate); if (date < event.startDate || date > event.endDate) throw new BadRequestException('Function date must fall within the event dates.'); const startAt = hotelLocalDateTimeToUtc(`${body.functionDate.slice(0, 10)}T${body.startTime}`, event.hotel.timezoneName); const endAt = hotelLocalDateTimeToUtc(`${body.functionDate.slice(0, 10)}T${body.endTime}`, event.hotel.timezoneName); if (endAt <= startAt) throw new BadRequestException('Function end time must be after the start time.'); const space = await this.p.functionSpace.findUnique({ where: { id: body.functionSpaceId } }); if (!space || space.hotelId !== event.hotelId) throw new BadRequestException('Function space does not belong to the event hotel.'); if (body.status !== BanquetFunctionStatus.CANCELLED && (!space.active || space.outOfService)) throw new ConflictException(`${space.name} is currently unavailable.`); const capacity = capacityFor(space, body.setupStyle); const pax = body.guaranteedPax ?? body.expectedPax; if (pax !== undefined && capacity !== null && pax > capacity) throw new BadRequestException(`${space.name} supports ${capacity} guests in ${body.setupStyle} setup; requested PAX is ${pax}.`); return { event, date, startAt, endAt, space, pax, functionId };
  }

  async createFunction(userId: string, eventId: string, body: BanquetFunctionCreateDto) {
    if (body.status === BanquetFunctionStatus.CANCELLED) throw new BadRequestException('A new function cannot start as cancelled.'); const input = await this.functionInput(userId, eventId, body); const row = await this.p.$transaction(async (tx) => { await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`${input.event.hotelId}:${body.functionSpaceId}:${body.functionDate}`}, 0))`; const conflict = await tx.banquetFunction.findFirst({ where: { functionSpaceId: body.functionSpaceId, status: ACTIVE_FUNCTION_STATUSES, banquetEvent: { status: { notIn: [BanquetEventStatus.CANCELLED, BanquetEventStatus.COMPLETED] } }, startAt: { lt: input.endAt }, endAt: { gt: input.startAt } }, include: { banquetEvent: { select: { eventCode: true, eventName: true } }, functionSpace: { select: { name: true } } } }); if (conflict) throw new ConflictException(`${conflict.functionSpace.name} is already booked from ${conflict.startTime} to ${conflict.endTime} for ${conflict.banquetEvent.eventName} (${conflict.banquetEvent.eventCode}).`); const created = await tx.banquetFunction.create({ data: { banquetEventId: eventId, functionSpaceId: body.functionSpaceId, functionName: body.functionName.trim(), functionDate: input.date, startTime: body.startTime, endTime: body.endTime, startAt: input.startAt, endAt: input.endAt, setupStyle: body.setupStyle, expectedPax: body.expectedPax, guaranteedPax: body.guaranteedPax, status: body.status ?? BanquetFunctionStatus.TENTATIVE, notes: clean(body.notes) }, include: { functionSpace: true } }); await tx.auditLog.create({ data: { actorUserId: userId, action: 'BANQUET_FUNCTION_CREATED', entityType: 'BanquetFunction', entityId: created.id, after: { eventId, hotelId: input.event.hotelId, functionSpaceId: body.functionSpaceId, startAt: input.startAt, endAt: input.endAt } } }); return created; }); return row;
  }

  async updateFunction(userId: string, eventId: string, functionId: string, body: BanquetFunctionUpdateDto) {
    const current = await this.p.banquetFunction.findFirst({ where: { id: functionId, banquetEventId: eventId }, include: { banquetEvent: { include: { hotel: { select: { timezoneName: true, id: true } } } } } }); if (!current) throw new NotFoundException('Banquet function not found.'); if (current.status === BanquetFunctionStatus.COMPLETED && body.status !== BanquetFunctionStatus.COMPLETED) throw new BadRequestException('A completed function cannot be edited.'); const input = await this.functionInput(userId, eventId, body); const row = await this.p.$transaction(async (tx) => { await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`${input.event.hotelId}:${body.functionSpaceId}:${body.functionDate}`}, 0))`; const conflict = await tx.banquetFunction.findFirst({ where: { id: { not: functionId }, functionSpaceId: body.functionSpaceId, status: ACTIVE_FUNCTION_STATUSES, banquetEvent: { status: { notIn: [BanquetEventStatus.CANCELLED, BanquetEventStatus.COMPLETED] } }, startAt: { lt: input.endAt }, endAt: { gt: input.startAt } }, include: { banquetEvent: { select: { eventCode: true, eventName: true } }, functionSpace: { select: { name: true } } } }); if (conflict) throw new ConflictException(`${conflict.functionSpace.name} is already booked from ${conflict.startTime} to ${conflict.endTime} for ${conflict.banquetEvent.eventName} (${conflict.banquetEvent.eventCode}).`); const updated = await tx.banquetFunction.update({ where: { id: functionId }, data: { functionSpaceId: body.functionSpaceId, functionName: body.functionName.trim(), functionDate: input.date, startTime: body.startTime, endTime: body.endTime, startAt: input.startAt, endAt: input.endAt, setupStyle: body.setupStyle, expectedPax: body.expectedPax, guaranteedPax: body.guaranteedPax, status: body.status, notes: body.notes === undefined ? undefined : clean(body.notes) }, include: { functionSpace: true } }); await tx.auditLog.create({ data: { actorUserId: userId, action: body.status === BanquetFunctionStatus.CANCELLED ? 'BANQUET_FUNCTION_CANCELLED' : current.functionSpaceId === body.functionSpaceId ? 'BANQUET_FUNCTION_UPDATED' : 'BANQUET_FUNCTION_MOVED', entityType: 'BanquetFunction', entityId: functionId, after: { eventId, functionSpaceId: body.functionSpaceId, startAt: input.startAt, endAt: input.endAt, status: updated.status } } }); return updated; }); return row;
  }

  async availability(userId: string, query: FunctionAvailabilityQueryDto) {
    const hotel = await this.assertHotel(userId, query.hotelId); const startAt = hotelLocalDateTimeToUtc(`${query.date.slice(0, 10)}T${query.startTime}`, hotel.timezoneName); const endAt = hotelLocalDateTimeToUtc(`${query.date.slice(0, 10)}T${query.endTime}`, hotel.timezoneName); if (endAt <= startAt) throw new BadRequestException('End time must be after start time.'); const spaces = await this.p.functionSpace.findMany({ where: { hotelId: hotel.id, active: true, outOfService: false }, orderBy: { name: 'asc' } }); const conflicts = await this.p.banquetFunction.findMany({ where: { functionSpaceId: { in: spaces.map((space) => space.id) }, status: ACTIVE_FUNCTION_STATUSES, banquetEvent: { status: { notIn: [BanquetEventStatus.CANCELLED, BanquetEventStatus.COMPLETED] } }, startAt: { lt: endAt }, endAt: { gt: startAt } }, include: { banquetEvent: { select: { eventCode: true, eventName: true } } } }); return spaces.map((space) => { const conflict = conflicts.find((item) => item.functionSpaceId === space.id); const capacity = query.setupStyle ? capacityFor(space, query.setupStyle) : null; return { space, capacity, available: !conflict && (query.pax === undefined || capacity === null || capacity >= query.pax), conflict: conflict ? { eventCode: conflict.banquetEvent.eventCode, eventName: conflict.banquetEvent.eventName, startTime: conflict.startTime, endTime: conflict.endTime } : null }; });
  }

  async calendar(userId: string, query: BanquetCalendarQueryDto) {
    const hotel = await this.assertHotel(userId, query.hotelId); const days = Math.min(7, Math.max(1, Number(query.days) || 1)); const from = localDate(query.from); const to = new Date(from); to.setUTCDate(to.getUTCDate() + days - 1); const rows = await this.p.banquetFunction.findMany({ where: { banquetEvent: { hotelId: hotel.id, status: { notIn: [BanquetEventStatus.CANCELLED, BanquetEventStatus.COMPLETED] } }, functionDate: { gte: from, lte: to }, status: ACTIVE_FUNCTION_STATUSES, OR: query.search ? [{ functionName: { contains: query.search, mode: 'insensitive' } }, { banquetEvent: { eventName: { contains: query.search, mode: 'insensitive' } } }, { functionSpace: { name: { contains: query.search, mode: 'insensitive' } } }] : undefined }, orderBy: [{ functionDate: 'asc' }, { startAt: 'asc' }], include: { functionSpace: true, banquetEvent: { select: { id: true, eventCode: true, eventName: true, status: true } }, beo: { select: { status: true, requirements: { select: { status: true } } } } } }); return { hotel, from: toDateOnly(from), to: toDateOnly(to), days, functions: rows.map((row) => ({ ...row, readiness: { beo: row.beo?.status ?? 'MISSING', requirements: row.beo ? `${row.beo.requirements.filter((item) => item.status === 'COMPLETED').length}/${row.beo.requirements.length}` : '0/0' } })) };
  }

  async createBeo(userId: string, eventId: string, functionId: string) {
    const fn = await this.p.banquetFunction.findFirst({ where: { id: functionId, banquetEventId: eventId }, include: { banquetEvent: { include: { hotel: { select: { id: true, code: true, timezoneName: true } } } } } }); if (!fn) throw new NotFoundException('Banquet function not found.'); await this.assertHotel(userId, fn.banquetEvent.hotelId, true); const row = await this.p.$transaction(async (tx) => { const existing = await tx.banquetEventOrder.findUnique({ where: { banquetFunctionId: functionId } }); if (existing) return existing; const year = fn.functionDate.getUTCFullYear(); await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`${fn.banquetEvent.hotelId}:BANQUET_BEO:${year}`}, 0))`; const beoNumber = await nextDocumentNumber(tx, fn.banquetEvent.hotelId, 'BANQUET_BEO', year, `BEO-${fn.banquetEvent.hotel.code}`); const beo = await tx.banquetEventOrder.create({ data: { banquetFunctionId: functionId, beoNumber } }); await tx.auditLog.create({ data: { actorUserId: userId, action: 'BEO_CREATED', entityType: 'BanquetEventOrder', entityId: beo.id, after: { eventId, functionId, beoNumber } } }); return beo; }); return this.beoDetail(userId, eventId, functionId);
  }

  private async beoDetail(userId: string, eventId: string, functionId: string) { const detail = await this.detail(userId, eventId); const fn = detail.functions.find((item: any) => item.id === functionId); if (!fn) throw new NotFoundException('Banquet function not found.'); return fn.beo ?? null; }

  async updateBeo(userId: string, eventId: string, functionId: string, body: BeoUpdateDto) {
    const fn = await this.p.banquetFunction.findFirst({ where: { id: functionId, banquetEventId: eventId }, include: { banquetEvent: true, beo: true } }); if (!fn?.beo) throw new NotFoundException('BEO not found.'); await this.assertHotel(userId, fn.banquetEvent.hotelId, true); const row = await this.p.$transaction(async (tx) => { if (fn.beo!.status === BanquetBEOStatus.FINAL) { await tx.auditLog.create({ data: { actorUserId: userId, action: 'BEO_REOPENED', entityType: 'BanquetEventOrder', entityId: fn.beo!.id, after: { reason: 'Edited after finalization' } } }); } if (body.schedule !== undefined) { await tx.banquetScheduleItem.deleteMany({ where: { beoId: fn.beo!.id } }); if (body.schedule.length) await tx.banquetScheduleItem.createMany({ data: body.schedule.map((item: BeoScheduleItemDto, index: number) => ({ beoId: fn.beo!.id, itemTime: item.itemTime, description: item.description.trim(), sortOrder: item.sortOrder ?? index })) }); } if (body.requirements !== undefined) { await tx.banquetRequirement.deleteMany({ where: { beoId: fn.beo!.id } }); if (body.requirements.length) await tx.banquetRequirement.createMany({ data: body.requirements.map((item: BeoRequirementDto) => ({ beoId: fn.beo!.id, category: item.category, description: item.description.trim(), quantity: item.quantity, requiredAt: clean(item.requiredAt), department: item.department.trim().toUpperCase(), notes: clean(item.notes), status: item.status })) }); } if (body.charges !== undefined) { await tx.banquetChargeLine.deleteMany({ where: { beoId: fn.beo!.id } }); if (body.charges.length) await tx.banquetChargeLine.createMany({ data: body.charges.map((item: BeoChargeLineDto) => ({ beoId: fn.beo!.id, category: item.category, description: item.description.trim(), quantity: item.quantity, unitAmount: money(item.unitAmount), totalAmount: money(item.quantity * item.unitAmount), notes: clean(item.notes) })) }); } return tx.banquetEventOrder.update({ where: { id: fn.beo!.id }, data: { status: BanquetBEOStatus.DRAFT, finalizedAt: null, finalizedById: null, operationalNotes: body.operationalNotes === undefined ? undefined : clean(body.operationalNotes) } }); }); await this.audit.log({ actorUserId: userId, action: 'BEO_UPDATED', entityType: 'BanquetEventOrder', entityId: row.id, after: { scheduleCount: body.schedule === undefined ? 'preserved' : body.schedule.length, requirementCount: body.requirements === undefined ? 'preserved' : body.requirements.length, chargeCount: body.charges === undefined ? 'preserved' : body.charges.length } }); return this.beoDetail(userId, eventId, functionId);
  }

  async finalizeBeo(userId: string, eventId: string, functionId: string) { const fn = await this.p.banquetFunction.findFirst({ where: { id: functionId, banquetEventId: eventId }, include: { banquetEvent: true, beo: { include: { requirements: true } } } }); if (!fn?.beo) throw new NotFoundException('BEO not found.'); await this.assertHotel(userId, fn.banquetEvent.hotelId, true); if (!fn.beo.requirements.length) throw new BadRequestException('Add at least one operational requirement before finalizing the BEO.'); const row = await this.p.banquetEventOrder.update({ where: { id: fn.beo.id }, data: { status: BanquetBEOStatus.FINAL, finalizedAt: new Date(), finalizedById: userId } }); await this.audit.log({ actorUserId: userId, action: 'BEO_FINALIZED', entityType: 'BanquetEventOrder', entityId: row.id, after: { beoNumber: row.beoNumber, functionId } }); return this.beoDetail(userId, eventId, functionId); }

  async updateRequirement(userId: string, eventId: string, functionId: string, requirementId: string, status: string) { const fn = await this.p.banquetFunction.findFirst({ where: { id: functionId, banquetEventId: eventId }, include: { banquetEvent: true, beo: true } }); if (!fn?.beo) throw new NotFoundException('BEO not found.'); await this.assertHotel(userId, fn.banquetEvent.hotelId, true); const row = await this.p.banquetRequirement.update({ where: { id: requirementId, beoId: fn.beo.id }, data: { status: status as any } }); await this.audit.log({ actorUserId: userId, action: 'BEO_REQUIREMENT_UPDATED', entityType: 'BanquetRequirement', entityId: row.id, after: { status: row.status, beoId: fn.beo.id } }); return row; }
}
