import { BookingSource, InquiryFollowUpMethod, InquiryStatus } from '@prisma/client';
import { IsDateString, IsEmail, IsEnum, IsInt, IsNumber, IsOptional, IsString, Min, MinLength } from 'class-validator';

export class InquiryListQueryDto { @IsOptional() @IsString() hotelId?: string; @IsOptional() @IsEnum(InquiryStatus) status?: InquiryStatus; @IsOptional() @IsEnum(BookingSource) source?: BookingSource; @IsOptional() @IsString() assignedToId?: string; @IsOptional() @IsDateString() stayFrom?: string; @IsOptional() @IsDateString() stayTo?: string; @IsOptional() @IsDateString() followUpTo?: string; @IsOptional() @IsString() search?: string; }
export class InquiryCreateDto { @IsString() hotelId!: string; @IsString() @MinLength(2) guestName!: string; @IsString() @MinLength(5) mobile!: string; @IsOptional() @IsEmail() email?: string; @IsEnum(BookingSource) source!: BookingSource; @IsOptional() @IsDateString() checkIn?: string; @IsOptional() @IsDateString() checkOut?: string; @IsOptional() @IsInt() @Min(1) adults?: number; @IsOptional() @IsInt() @Min(0) children?: number; @IsOptional() @IsString() roomTypeId?: string; @IsOptional() @IsString() assignedToId?: string; @IsOptional() @IsDateString() nextFollowUpAt?: string; @IsOptional() @IsString() notes?: string; }
export class InquiryUpdateDto { @IsOptional() @IsString() @MinLength(2) guestName?: string; @IsOptional() @IsString() mobile?: string; @IsOptional() @IsEmail() email?: string; @IsOptional() @IsEnum(InquiryStatus) status?: InquiryStatus; @IsOptional() @IsEnum(BookingSource) source?: BookingSource; @IsOptional() @IsDateString() checkIn?: string; @IsOptional() @IsDateString() checkOut?: string; @IsOptional() @IsInt() @Min(1) adults?: number; @IsOptional() @IsInt() @Min(0) children?: number; @IsOptional() @IsString() roomTypeId?: string; @IsOptional() @IsString() assignedToId?: string; @IsOptional() @IsDateString() nextFollowUpAt?: string; @IsOptional() @IsString() notes?: string; }
export class InquiryFollowUpDto { @IsEnum(InquiryFollowUpMethod) method!: InquiryFollowUpMethod; @IsString() @MinLength(1) note!: string; @IsOptional() @IsDateString() nextFollowUpAt?: string; }
export class InquiryQuoteDto { @IsNumber() @Min(0) quotedAmount!: number; @IsOptional() quoteSnapshot?: unknown; }
export class InquiryConvertDto { @IsString() reservationReference!: string; }
export class InquiryLostDto { @IsString() @MinLength(1) lostReason!: string; }
