'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { AdminLayout } from '../../../../components/Shell';
import { API, apiRequest } from '../../../../lib/api';

const steps = ['Basic Info', 'Rooms', 'Amenities', 'Price Book', 'Review', 'Preview'];
type OccupancyKey = 'single' | 'double' | 'triple' | 'quad' | 'extrabed' | 'extraadult' | 'extrachild' | 'extraadult2' | 'extrachild2' | 'extraadult3' | 'extrachild3' | 'extrainfant';
type InventoryDay = { id: string; date: string; available: number; stopSell: boolean };
type RateDay = { id: string; date: string; amount: string | number; taxAmount: string | number; occupancyPrices?: Partial<Record<OccupancyKey, string | number>> };
type RatePlan = { id: string; code?: string; name: string; mealPlan: string; rates: RateDay[] };
type Room = { id: string; code: string; name: string; ratePlans: RatePlan[]; inventory: InventoryDay[] };
type HotelImage = { id: string; url: string; altText: string; sortOrder: number; published: boolean };
type Hotel = { id: string; code?: string; name: string; slug: string; city: string; description?: string | null; active?: boolean; seoTitle?: string | null; seoDescription?: string | null; canonicalPath?: string | null; ogImageUrl?: string | null; images?: HotelImage[]; rooms?: Room[]; amenities?: { amenity: { name: string } }[] };
type DateRange = { id: string; start: string; end: string };
type PricingValues = { amount: number; taxAmount: number; occupancyPrices: Record<OccupancyKey, number> };
type InventoryValues = { available: number; stopSell: boolean };
const occupancyFields: { key: OccupancyKey; label: string }[] = [{ key: 'single', label: 'Single (INR)' }, { key: 'double', label: 'Double (INR)' }, { key: 'triple', label: 'Triple (INR)' }, { key: 'quad', label: 'Quad (INR)' }, { key: 'extrabed', label: 'Extra bed (INR)' }, { key: 'extraadult', label: 'Extra adult (INR)' }, { key: 'extrachild', label: 'Extra child (INR)' }, { key: 'extraadult2', label: 'Extra adult 2 (INR)' }, { key: 'extrachild2', label: 'Extra child 2 (INR)' }, { key: 'extraadult3', label: 'Extra adult 3 (INR)' }, { key: 'extrachild3', label: 'Extra child 3 (INR)' }, { key: 'extrainfant', label: 'Extra infant (INR)' }];
const blankHotel = { code: '', name: '', slug: '', city: '', description: '', active: true, seoTitle: '', seoDescription: '', canonicalPath: '', ogImageUrl: '' };
const blankRoom = { code: '', name: '', description: '', maxAdults: 2, maxChildren: 1, maxOccupancy: 3 };
function datesBetween(start: string, end: string) { const out: string[] = []; const cursor = new Date(`${start}T00:00:00Z`); const last = new Date(`${end}T00:00:00Z`); while (start && end && cursor <= last && out.length < 370) { out.push(cursor.toISOString().slice(0, 10)); cursor.setUTCDate(cursor.getUTCDate() + 1); } return out; }
function rangesFromDates(dates: string[]) { const sorted = Array.from(new Set(dates.map((date) => date.slice(0, 10)))).sort(); const ranges: DateRange[] = []; let start = ''; let previous = ''; sorted.forEach((date) => { if (!start) { start = date; previous = date; return; } const next = new Date(`${previous}T00:00:00Z`); next.setUTCDate(next.getUTCDate() + 1); if (formatDate(next) !== date) { ranges.push({ id: `saved-${start}-${previous}`, start, end: previous }); start = date; } previous = date; }); if (start) ranges.push({ id: `saved-${start}-${previous}`, start, end: previous }); return ranges; }
function formatDate(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function endOfMonth(date: Date) { return new Date(date.getFullYear(), date.getMonth() + 1, 0); }
function defaultDateRange() { const today = new Date(); return { start: formatDate(today), end: formatDate(endOfMonth(today)) }; }
function nextDateRange(lastEnd: string) { const next = new Date(`${lastEnd}T00:00:00`); next.setDate(next.getDate() + 1); return { start: formatDate(next), end: formatDate(endOfMonth(next)) }; }
function emptyPricing(): PricingValues { return { amount: 0, taxAmount: 0, occupancyPrices: { single: 0, double: 0, triple: 0, quad: 0, extrabed: 0, extraadult: 0, extrachild: 0, extraadult2: 0, extrachild2: 0, extraadult3: 0, extrachild3: 0, extrainfant: 0 } }; }

export default function NewHotelWizard() {
  const searchParams = useSearchParams(); const editId = searchParams.get('edit') ?? ''; const initialStep = Number(searchParams.get('step') ?? 0);
  const [step, setStep] = useState(Number.isFinite(initialStep) ? initialStep : 0); const [hotel, setHotel] = useState(blankHotel); const [hotelId, setHotelId] = useState(editId); const [catalog, setCatalog] = useState<Hotel | null>(null); const [room, setRoom] = useState(blankRoom); const [amenity, setAmenity] = useState({ code: '', name: '' });
  const [selectedRoomId, setSelectedRoomId] = useState('ALL'); const [selectedPlanKey, setSelectedPlanKey] = useState(''); const [dateRanges, setDateRanges] = useState<DateRange[]>([]); const [draftRange, setDraftRange] = useState(defaultDateRange); const [hiddenPricingRangeIds, setHiddenPricingRangeIds] = useState<string[]>([]); const [inventoryDateRanges, setInventoryDateRanges] = useState<DateRange[]>([]); const [inventoryDraftRange, setInventoryDraftRange] = useState(defaultDateRange); const [hiddenInventoryRangeIds, setHiddenInventoryRangeIds] = useState<string[]>([]); const [pricingByRoom, setPricingByRoom] = useState<Record<string, PricingValues>>({}); const [inventoryByRoom, setInventoryByRoom] = useState<Record<string, InventoryValues>>({});
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [imageFiles, setImageFiles] = useState<File[]>([]);
  async function loadCatalog(id = hotelId) { if (id) setCatalog(await apiRequest<Hotel>(`/hotels/${id}/catalog`)); }
  useEffect(() => { if (hotelId) void loadCatalog(); }, [hotelId]);
  useEffect(() => { if (!editId) return; apiRequest<Hotel>(`/hotels/${editId}/catalog`).then((data) => { setHotelId(editId); setHotel({ code: data.code ?? '', name: data.name, slug: data.slug, city: data.city, description: data.description ?? '', active: data.active ?? true, seoTitle: data.seoTitle ?? '', seoDescription: data.seoDescription ?? '', canonicalPath: data.canonicalPath ?? '', ogImageUrl: data.ogImageUrl ?? '' }); setCatalog(data); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load hotel')); }, [editId]);
  const rooms = catalog?.rooms ?? [];
  useEffect(() => { setDraftRange(dateRanges.length ? nextDateRange(dateRanges[dateRanges.length - 1].end) : defaultDateRange()); }, [dateRanges]); useEffect(() => { setInventoryDraftRange(inventoryDateRanges.length ? nextDateRange(inventoryDateRanges[inventoryDateRanges.length - 1].end) : defaultDateRange()); }, [inventoryDateRanges]); useEffect(() => { if (step !== 3 && (dateRanges.length || inventoryDateRanges.length)) { setDateRanges([]); setInventoryDateRanges([]); setHiddenPricingRangeIds([]); setHiddenInventoryRangeIds([]); } }, [step, dateRanges.length, inventoryDateRanges.length]);
  useEffect(() => { if (!rooms.length) return; const firstPlan = rooms.flatMap((item) => item.ratePlans)[0]; if (!selectedPlanKey && firstPlan) { setSelectedPlanKey(firstPlan.code ?? firstPlan.id); return; } if (selectedPlanKey) setPricingByRoom(Object.fromEntries(rooms.map((item) => { const plan = item.ratePlans.find((ratePlan) => (ratePlan.code ?? ratePlan.id) === selectedPlanKey); const values = emptyPricing(); const rate = plan?.rates?.[0]; values.amount = Number(rate?.amount ?? 0); values.taxAmount = Number(rate?.taxAmount ?? 0); occupancyFields.forEach((field) => { values.occupancyPrices[field.key] = Number(rate?.occupancyPrices?.[field.key] ?? 0); }); return [item.id, values]; }))); }, [rooms, selectedPlanKey]);
  useEffect(() => { if (!rooms.length) return; setInventoryByRoom((current) => { const next = { ...current }; rooms.forEach((item) => { if (!next[item.id]) next[item.id] = { available: Number(item.inventory?.[0]?.available ?? 0), stopSell: Boolean(item.inventory?.[0]?.stopSell) }; }); return next; }); }, [rooms]);
  async function request(path: string, body: unknown, method: 'POST' | 'PATCH' = 'POST') { setBusy(true); setError(''); setMessage(''); try { const result = await apiRequest<{ id?: string }>(path, { method, body: JSON.stringify(body) }); setMessage('Saved successfully.'); return result; } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save'); return null; } finally { setBusy(false); } }
  async function uploadHotelImages(id: string) { for (const [index, file] of imageFiles.entries()) { const formData = new FormData(); formData.append('file', file); const stored = await apiRequest<{ id: string }>(`/files/hotel-image`, { method: 'POST', body: formData }); await apiRequest(`/hotels/${id}/images`, { method: 'POST', body: JSON.stringify({ url: `${API}/files/public/${stored.id}`, altText: file.name.replace(/\.[^.]+$/, ''), sortOrder: index }) }); } setImageFiles([]); }
  async function downloadPriceBook() { if (!hotelId) return; setBusy(true); setError(''); try { const token = window.localStorage.getItem('rainwood_access_token'); const response = await fetch(`${API}/hotels/${hotelId}/pricebook.xlsx`, { credentials: 'include', headers: token ? { Authorization: `Bearer ${token}` } : undefined }); if (!response.ok) throw new Error('Could not download the price book.'); const blob = await response.blob(); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${hotel.slug || 'rainwood-hotel'}-pricebook.xlsx`; link.click(); URL.revokeObjectURL(link.href); setMessage('Price book Excel downloaded successfully.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not download the price book'); } finally { setBusy(false); } }
  async function deleteHotelImage(image: HotelImage) { if (!hotelId || !window.confirm(`Delete ${image.altText}? This removes the gallery link and uploaded file permanently.`)) return; try { await apiRequest(`/hotels/${hotelId}/images/${image.id}`, { method: 'DELETE' }); setCatalog((current) => current ? { ...current, images: current.images?.filter((item) => item.id !== image.id) } : current); setMessage('Image deleted successfully.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not delete image'); } }
  async function nextFromBasic(event: FormEvent) { event.preventDefault(); const result = await request(hotelId ? `/hotels/${hotelId}` : '/hotels', { ...hotel, slug: hotel.slug.trim().toLowerCase() }, hotelId ? 'PATCH' : 'POST'); const savedId = hotelId || result?.id; if (savedId) { if (result?.id) setHotelId(result.id); if (imageFiles.length) { setBusy(true); try { await uploadHotelImages(savedId); setMessage('Hotel details and images saved successfully.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Hotel saved, but image upload failed'); } finally { setBusy(false); } } setStep(1); } }
  async function addRoom(event: FormEvent) { event.preventDefault(); if (!hotelId) return; const result = await request(`/hotels/${hotelId}/rooms`, room); if (result) { setRoom(blankRoom); await loadCatalog(); } }
  async function addAmenity(event: FormEvent) { event.preventDefault(); if (!hotelId) return; const result = await request(`/hotels/${hotelId}/amenities`, amenity); if (result) { setAmenity({ code: '', name: '' }); await loadCatalog(); } }
  const selectedRooms = selectedRoomId === 'ALL' ? rooms : rooms.filter((item) => item.id === selectedRoomId); const planOptions = Array.from(new Map(rooms.flatMap((item) => item.ratePlans.map((plan) => [plan.code ?? plan.id, plan] as const))).values()); const selectedPlan = planOptions.find((item) => (item.code ?? item.id) === selectedPlanKey); const selectedDates = Array.from(new Set(dateRanges.flatMap((item) => datesBetween(item.start, item.end)))); const selectedInventoryDates = Array.from(new Set(inventoryDateRanges.flatMap((item) => datesBetween(item.start, item.end)))); const savedPricingRanges = rangesFromDates(selectedRooms.flatMap((roomItem) => roomItem.ratePlans.filter((plan) => (plan.code ?? plan.id) === selectedPlanKey).flatMap((plan) => plan.rates.map((rate) => rate.date)))); const savedInventoryRanges = rangesFromDates(selectedRooms.flatMap((roomItem) => roomItem.inventory.map((day) => day.date))); const pricingDisplayRanges = Array.from(new Map([...dateRanges, ...savedPricingRanges.filter((item) => !hiddenPricingRangeIds.includes(item.id))].map((item) => [`${item.start}-${item.end}`, item] as const)).values()); const inventoryDisplayRanges = Array.from(new Map([...inventoryDateRanges, ...savedInventoryRanges.filter((item) => !hiddenInventoryRangeIds.includes(item.id))].map((item) => [`${item.start}-${item.end}`, item] as const)).values());
  function addInventoryDateRange() { if (!inventoryDraftRange.start || !inventoryDraftRange.end || !datesBetween(inventoryDraftRange.start, inventoryDraftRange.end).length) { setError('Enter a valid inventory start and end date.'); return; } if (inventoryDateRanges.some((item) => item.start === inventoryDraftRange.start && item.end === inventoryDraftRange.end)) { setError('That inventory date range is already added.'); return; } setError(''); setInventoryDateRanges((current) => [...current, { id: `${Date.now()}-${inventoryDraftRange.start}`, ...inventoryDraftRange }]); setInventoryDraftRange({ start: '', end: '' }); }
  function addDateRange() { if (!draftRange.start || !draftRange.end || !datesBetween(draftRange.start, draftRange.end).length) { setError('Enter a valid start and end date.'); return; } if (dateRanges.some((item) => item.start === draftRange.start && item.end === draftRange.end)) { setError('That date range is already added.'); return; } setError(''); setDateRanges((current) => [...current, { id: `${Date.now()}-${draftRange.start}`, ...draftRange }]); setDraftRange({ start: '', end: '' }); }
  function removePricingRange(item: DateRange) { setDateRanges((current) => current.filter((range) => range.id !== item.id)); if (item.id.startsWith('saved-')) setHiddenPricingRangeIds((current) => [...current, item.id]); }
  function removeInventoryRange(item: DateRange) { setInventoryDateRanges((current) => current.filter((range) => range.id !== item.id)); if (item.id.startsWith('saved-')) setHiddenInventoryRangeIds((current) => [...current, item.id]); }
  function updatePricing(roomId: string, patch: Partial<PricingValues>) { setPricingByRoom((current) => ({ ...current, [roomId]: { ...(current[roomId] ?? emptyPricing()), ...patch } })); }
  function updateInventory(roomId: string, patch: Partial<InventoryValues>) { setInventoryByRoom((current) => ({ ...current, [roomId]: { ...(current[roomId] ?? { available: 0, stopSell: false }), ...patch } })); }
  async function savePriceBook() { if (!selectedRooms.length || !selectedPlanKey || !selectedDates.length) { setError('Select a room, rate plan, and add at least one valid date range for pricing.'); return; } for (const target of selectedRooms) { const plan = target.ratePlans.find((item) => (item.code ?? item.id) === selectedPlanKey); if (!plan) { setError(`Rate plan is not configured for ${target.name}.`); return; } const values = pricingByRoom[target.id] ?? emptyPricing(); await request(`/hotels/rate-plans/${plan.id}/rates`, { days: selectedDates.map((date) => ({ date, amount: Number(values.amount || values.occupancyPrices.double || values.occupancyPrices.single), taxAmount: Number(values.taxAmount), occupancyPrices: values.occupancyPrices })) }); } await loadCatalog(); setMessage(`Pricing saved for ${selectedRooms.length} room${selectedRooms.length === 1 ? '' : 's'} across ${selectedDates.length} date${selectedDates.length === 1 ? '' : 's'}.`); }
  async function saveInventoryBook() { if (!selectedRooms.length || !selectedInventoryDates.length) { setError('Select a room and add at least one valid date range for inventory.'); return; } for (const target of selectedRooms) { const values = inventoryByRoom[target.id] ?? { available: 0, stopSell: false }; await request(`/hotels/rooms/${target.id}/inventory`, { days: selectedInventoryDates.map((date) => ({ date, available: Number(values.available), stopSell: values.stopSell })) }); } await loadCatalog(); setMessage(`Inventory saved for ${selectedRooms.length} room${selectedRooms.length === 1 ? '' : 's'} across ${selectedInventoryDates.length} date${selectedInventoryDates.length === 1 ? '' : 's'}.`); }
  return <AdminLayout title={editId ? 'Edit Hotel' : 'Add Hotel'}><div className="wizard"><div className="wizardHeader"><div><span>Hotel setup</span><h2>{editId ? 'Edit property step by step' : 'Create property step by step'}</h2></div><Link className="btn secondary" href="/admin/hotels">Manage Hotels</Link></div><div className="wizardSteps">{steps.map((label, index) => <button type="button" className={`wizardStep ${index === step ? 'active' : index < step ? 'done' : ''}`} disabled={index > 0 && !hotelId} onClick={() => setStep(index)} key={label}><b>{index + 1}</b><span>{label}</span></button>)}</div>{error && <p className="error" role="alert">{error}</p>}{message && <p className="notice" role="status">{message}</p>}
    {step === 0 && <form className="formCard wizardCard" onSubmit={nextFromBasic}><h2>Basic Info</h2><div className="two"><label>Hotel name<input value={hotel.name} onChange={(e) => setHotel({ ...hotel, name: e.target.value })} required /></label><label>Place / city<input value={hotel.city} onChange={(e) => setHotel({ ...hotel, city: e.target.value })} required /></label></div><div className="two"><label>Hotel code<input value={hotel.code} onChange={(e) => setHotel({ ...hotel, code: e.target.value })} placeholder="RW-MUNNAR" required /></label><label>Slug<input value={hotel.slug} onChange={(e) => setHotel({ ...hotel, slug: e.target.value })} required /></label></div><label>Description<textarea value={hotel.description} onChange={(e) => setHotel({ ...hotel, description: e.target.value })} /></label><div className="two"><label>SEO title<input value={hotel.seoTitle} onChange={(e) => setHotel({ ...hotel, seoTitle: e.target.value })} /></label><label>Legacy hero image URL (optional)<input type="url" value={hotel.ogImageUrl} onChange={(e) => setHotel({ ...hotel, ogImageUrl: e.target.value })} /></label></div><label>Hotel gallery images (JPEG or PNG)<input type="file" accept="image/jpeg,image/png" multiple onChange={(e) => setImageFiles(Array.from(e.target.files ?? []))} /><small className="muted">These images are uploaded by Admin and used on public hotel cards and detail pages.</small></label>{catalog?.images?.length ? <div className="hotelImagePreview"><b>Uploaded images</b><div className="hotelImageThumbs">{catalog.images.map((image) => <div className="hotelImageThumb" key={image.id}><img src={image.url} alt={image.altText} title={image.altText} /><button type="button" className="hotelImageDelete" aria-label={`Delete ${image.altText}`} title="Delete image" onClick={() => void deleteHotelImage(image)}>×</button></div>)}</div></div> : null}<WizardButtons busy={busy} next="Save & Continue" /></form>}
    {step === 1 && <section className="formCard wizardCard"><h2>Rooms</h2><p>Add one or more room categories before continuing.</p><form onSubmit={addRoom}><div className="two"><label>Room code<input value={room.code} onChange={(e) => setRoom({ ...room, code: e.target.value })} placeholder="DLX" required /></label><label>Room name<input value={room.name} onChange={(e) => setRoom({ ...room, name: e.target.value })} required /></label></div><label>Description<textarea value={room.description} onChange={(e) => setRoom({ ...room, description: e.target.value })} /></label><div className="three"><label>Adults<input type="number" min="1" value={room.maxAdults} onChange={(e) => setRoom({ ...room, maxAdults: Number(e.target.value) })} /></label><label>Children<input type="number" min="0" value={room.maxChildren} onChange={(e) => setRoom({ ...room, maxChildren: Number(e.target.value) })} /></label><label>Occupancy<input type="number" min="1" value={room.maxOccupancy} onChange={(e) => setRoom({ ...room, maxOccupancy: Number(e.target.value) })} /></label></div><button className="btn" disabled={busy}>Add room</button></form><div className="wizardList">{rooms.map((item) => <div key={item.id}><b>{item.name}</b><span>{item.code} | Capacity {item.ratePlans.length ? item.ratePlans.length + ' rate plans' : 'No rate plan yet'}</span></div>)}</div><WizardButtons onBack={() => setStep(0)} onNext={() => setStep(2)} /></section>}
    {step === 2 && <section className="formCard wizardCard"><h2>Amenities</h2><p>Add amenities that will appear on the public hotel detail page.</p><form onSubmit={addAmenity}><div className="two"><label>Code<input value={amenity.code} onChange={(e) => setAmenity({ ...amenity, code: e.target.value })} placeholder="WIFI" required /></label><label>Name<input value={amenity.name} onChange={(e) => setAmenity({ ...amenity, name: e.target.value })} placeholder="High-speed Wi-Fi" required /></label></div><button className="btn" disabled={busy}>Add amenity</button></form><div className="tagList">{catalog?.amenities?.map((item) => <span key={item.amenity.name}>{item.amenity.name}</span>)}</div><WizardButtons onBack={() => setStep(1)} onNext={() => setStep(3)} /></section>}
    {step === 3 && <section className="formCard wizardCard"><h2>Price Book</h2><p>Choose one rate plan, add multiple date ranges, and apply pricing and inventory to one or all rooms.</p><section className="rangeSubcard priceBookFilters"><div className="rangeSectionHeader"><h3>Price Book Filters</h3><button className="smallBtn" type="button" disabled={busy} onClick={() => void downloadPriceBook()}>Download Excel</button></div><div className="rangeToolbar"><label>Room<select value={selectedRoomId} onChange={(e) => setSelectedRoomId(e.target.value)}><option value="ALL">All rooms</option>{rooms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Rate plan<select value={selectedPlanKey} onChange={(e) => setSelectedPlanKey(e.target.value)}><option value="">Select rate plan</option>{planOptions.map((item) => <option key={item.code ?? item.id} value={item.code ?? item.id}>{item.name} - {item.mealPlan}</option>)}</select></label><label>Start date<input type="date" value={draftRange.start} onChange={(e) => setDraftRange({ ...draftRange, start: e.target.value })} onInput={(e) => { const value = e.currentTarget.value; setDraftRange((current) => ({ ...current, start: value })); }} /></label><label>End date<input type="date" value={draftRange.end} onChange={(e) => setDraftRange({ ...draftRange, end: e.target.value })} onInput={(e) => { const value = e.currentTarget.value; setDraftRange((current) => ({ ...current, end: value })); }} /></label><button className="smallBtn dateRangeAddButton" type="button" onClick={addDateRange}>Add date</button></div>{pricingDisplayRanges.length > 0 ? <div className="dateRangeList"><b>Date ranges</b>{pricingDisplayRanges.map((item) => <span key={item.id}>{item.start} - {item.end}<button type="button" aria-label={"Remove " + item.start + " - " + item.end} onClick={() => removePricingRange(item)}>x</button></span>)}</div> : <p className="muted">Add one or more date ranges for pricing.</p>}{dateRanges.length > 0 && <button className="smallBtn rangeDateSave" type="button" disabled={busy || !selectedDates.length || !selectedPlanKey} onClick={() => void savePriceBook()}>Save rates for date ranges</button>}</section>
      <section className="rangeSubcard"><div className="rangeSectionHeader"><h3>Room Details / Pricing</h3></div>{selectedRooms.length === 0 && <p className="muted">Add a room first.</p>}{selectedRooms.map((item) => { const values = pricingByRoom[item.id] ?? emptyPricing(); const roomPlan = item.ratePlans.find((plan) => (plan.code ?? plan.id) === selectedPlanKey); return <div className="roomForm" key={item.id}><h3>{item.name}</h3><p className="muted">{roomPlan ? `${roomPlan.name} - ${roomPlan.mealPlan}` : 'Selected rate plan is not configured for this room.'}</p><div className="occupancyGrid">{occupancyFields.map((field) => <label key={field.key}>{field.label}<input type="number" min="0" step="0.01" value={values.occupancyPrices[field.key]} onChange={(e) => updatePricing(item.id, { occupancyPrices: { ...values.occupancyPrices, [field.key]: Number(e.target.value) } })} /></label>)}</div><label>Base amount<input type="number" min="0" step="0.01" value={values.amount} onChange={(e) => updatePricing(item.id, { amount: Number(e.target.value) })} /></label><label>Tax amount<input type="number" min="0" step="0.01" value={values.taxAmount} onChange={(e) => updatePricing(item.id, { taxAmount: Number(e.target.value) })} /></label><button className="smallBtn roomPricingSave" type="button" disabled={busy || !selectedDates.length || !selectedPlanKey} onClick={() => void savePriceBook()}>Save pricing</button></div>; })}{selectedDates.length > 0 && <p className="muted">This will create/update {selectedDates.length} daily rate record(s) for each selected room.</p>}</section>
      <section className="rangeSubcard"><div className="rangeSectionHeader"><h3>Room Availability / Inventory</h3><button className="smallBtn" type="button" disabled={busy || !selectedInventoryDates.length} onClick={() => void saveInventoryBook()}>Save inventory</button></div><div className="rangeToolbar inventoryDateFilters"><label>Start date<input type="date" value={inventoryDraftRange.start} onChange={(e) => setInventoryDraftRange({ ...inventoryDraftRange, start: e.target.value })} onInput={(e) => { const value = e.currentTarget.value; setInventoryDraftRange((current) => ({ ...current, start: value })); }} /></label><label>End date<input type="date" value={inventoryDraftRange.end} onChange={(e) => setInventoryDraftRange({ ...inventoryDraftRange, end: e.target.value })} onInput={(e) => { const value = e.currentTarget.value; setInventoryDraftRange((current) => ({ ...current, end: value })); }} /></label><button className="smallBtn dateRangeAddButton" type="button" onClick={addInventoryDateRange}>Add date</button></div>{inventoryDisplayRanges.length > 0 ? <div className="dateRangeList"><b>Inventory date ranges</b>{inventoryDisplayRanges.map((item) => <span key={item.id}>{item.start} - {item.end}<button type="button" aria-label={"Remove inventory " + item.start + " - " + item.end} onClick={() => removeInventoryRange(item)}>x</button></span>)}</div> : <p className="muted">Add inventory date ranges independently from pricing.</p>}{selectedRooms.map((item) => { const values = inventoryByRoom[item.id] ?? { available: 0, stopSell: false }; return <div className="roomForm inventoryForm" key={item.id}><h3>{item.name}</h3><div className="two"><label>Available rooms<input type="number" min="0" value={values.available} onChange={(e) => updateInventory(item.id, { available: Number(e.target.value) })} /></label><label className="checkboxLabel"><input type="checkbox" checked={values.stopSell} onChange={(e) => updateInventory(item.id, { stopSell: e.target.checked })} /> Stop sell</label></div></div>; })}<button className="btn" type="button" disabled={busy || !selectedInventoryDates.length} onClick={() => void saveInventoryBook()}>Save inventory for selected rooms</button>{selectedInventoryDates.length > 0 && <p className="muted">This will create/update {selectedInventoryDates.length} daily inventory record(s) for each selected room.</p>}</section><WizardButtons onBack={() => setStep(2)} onNext={() => setStep(4)} /></section>}
    {step === 4 && <section className="formCard wizardCard"><h2>Review</h2><div className="reviewGrid"><div><span>Hotel</span><b>{hotel.name}</b><small>{hotel.city} - {hotel.code}</small></div><div><span>Rooms</span><b>{rooms.length}</b><small>{rooms.map((item) => item.name).join(', ') || 'None added'}</small></div><div><span>Amenities</span><b>{catalog?.amenities?.length ?? 0}</b><small>{catalog?.amenities?.map((item) => item.amenity.name).join(', ') || 'None added'}</small></div></div><WizardButtons onBack={() => setStep(3)} onNext={() => setStep(5)} next="Open Preview" /></section>}
    {step === 5 && <section className="formCard wizardCard previewCard"><span className="status ok">Ready</span><h2>{hotel.name}</h2><p>{hotel.description}</p><p>{hotel.city} - {rooms.length} room categories</p><div className="toolbar"><Link className="btn" href={`/hotels/${hotel.slug}`}>View public hotel</Link><Link className="btn secondary" href={`/admin/hotels/${hotelId}/catalog`}>Manage rooms & rates</Link></div></section>}
  </div></AdminLayout>;
}
function WizardButtons({ onBack, onNext, busy, next = 'Continue' }: { onBack?: () => void; onNext?: () => void; busy?: boolean; next?: string }) { return <div className="wizardButtons">{onBack && <button type="button" className="btn secondary" onClick={onBack}>Back</button>}{onNext && <button type="button" className="btn" onClick={onNext}>{next}</button>}{!onNext && <button className="btn" disabled={busy}>{busy ? 'Saving...' : next}</button>}</div>; }
