'use client';

import { useEffect, useState } from 'react';
import { apiRequest } from '../lib/api';
import { ArrivalDetailsModal } from './ArrivalDetailsModal';

type InHouseRow = { reference: string; guestName: string; hotel: { id: string; name: string }; arrival: string; departure: string; rooms: { roomNumber: string; roomType?: { name: string } | null; status: string }[]; roomTypes: string[]; pax: number; balance: number; incidentals: number; totalOutstanding: number; checkedInAt: string | null; checkedInBy: { name: string } | null };
function dateLabel(value: string | null) { return value ? new Date(value).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' }) : '—'; }
function money(value: number) { return `INR ${Number(value).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

export function AdminInHouse() {
  const [rows, setRows] = useState<InHouseRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState<string | null>(null);
  function load() { setLoading(true); apiRequest<InHouseRow[]>('/reservations/in-house').then(setRows).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load in-house guests.')).finally(() => setLoading(false)); }
  useEffect(() => { load(); }, []);
  return <section className="arrivalsPage"><div className="formCard arrivalsFilters"><div className="arrivalsFilterHeader"><div><span className="eyebrow">Front Desk Operations</span><h1>In-house Guests</h1><p>Only guests with an authoritative CHECKED_IN stay are shown.</p></div><button className="btn" type="button" onClick={load}>Refresh</button></div></div>{error && <p className="error" role="alert">{error}</p>}<section className="panel arrivalsTablePanel"><div className="arrivalsTableMeta"><span>{rows.length} in-house guest{rows.length === 1 ? '' : 's'}</span></div><div className="tableScroll"><table className="arrivalsTable"><thead><tr><th>Room</th><th>Guest</th><th>Reservation #</th><th>Room Type</th><th>Arrival</th><th>Departure</th><th>Pax</th><th>Balance</th><th>Incidentals</th><th>Total Outstanding</th><th>Checked In</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={12} className="loading">Loading in-house guests...</td></tr> : rows.map((row) => <tr key={row.reference}><td><strong>{row.rooms.map((room) => room.roomNumber).join(', ') || '—'}</strong></td><td>{row.guestName}</td><td><button className="arrivalsReservationLink" type="button" onClick={() => setSelected(row.reference)}>{row.reference}</button></td><td>{row.roomTypes.join(', ') || '—'}</td><td>{dateLabel(row.arrival)}</td><td>{dateLabel(row.departure)}</td><td>{row.pax}</td><td>{money(row.balance)}</td><td>{money(row.incidentals)}</td><td><strong>{money(row.totalOutstanding)}</strong></td><td>{dateLabel(row.checkedInAt)}{row.checkedInBy ? <small> · {row.checkedInBy.name}</small> : null}</td><td><button className="smallBtn" type="button" onClick={() => setSelected(row.reference)}>View</button></td></tr>)}{!loading && !rows.length && <tr><td colSpan={12} className="empty">No checked-in guests found.</td></tr>}</tbody></table></div></section>{selected && <ArrivalDetailsModal reference={selected} onClose={() => { setSelected(null); load(); }} onReconfirmed={() => undefined} />}</section>;
}
