'use client';

import { useEffect, useState } from 'react';
import { apiRequest } from '../lib/api';

type Requirement = { reservationLineId: string; roomType: { id: string; name: string }; requiredRooms: number; availableRooms: { id: string; roomNumber: string; floor: string | null; wing: string | null }[] };
type Available = { reservation: { reference: string; hotel: { name: string }; checkIn: string; checkOut: string }; requirements: Requirement[] };

export function CheckInDialog({ reference, onClose, onSuccess }: { reference: string; onClose: () => void; onSuccess: () => void }) {
  const [data, setData] = useState<Available | null>(null); const [selected, setSelected] = useState<Record<string, string[]>>({}); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { apiRequest<Available>(`/reservations/${encodeURIComponent(reference)}/available-rooms`).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load available rooms.')).finally(() => setLoading(false)); }, [reference]);
  function choose(lineId: string, index: number, roomId: string) { setSelected((current) => { const next = [...(current[lineId] ?? [])]; next[index] = roomId; return { ...current, [lineId]: next }; }); }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!data) return; const assignments = data.requirements.flatMap((requirement) => Array.from({ length: requirement.requiredRooms }, (_, index) => ({ reservationLineId: requirement.reservationLineId, roomId: selected[requirement.reservationLineId]?.[index] || '' }))); if (assignments.some((item) => !item.roomId) || new Set(assignments.map((item) => item.roomId)).size !== assignments.length) { setError('Select a different available room for every booked room.'); return; } setBusy(true); setError(''); try { await apiRequest(`/reservations/${encodeURIComponent(reference)}/check-in`, { method: 'POST', body: JSON.stringify({ assignments }) }); onSuccess(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not check in guest.'); } finally { setBusy(false); } }
  return <div className="arrivalFolioDialogBackdrop" role="presentation"><section className="arrivalFolioDialog" role="dialog" aria-modal="true" aria-labelledby="check-in-title"><header><div><span className="eyebrow">Front Desk Operations</span><h3 id="check-in-title">Check In Guest</h3><p>{reference} · {data?.reservation.hotel.name}</p></div><button className="uiModalClose" type="button" onClick={onClose} aria-label="Close check-in">×</button></header>{loading ? <p role="status">Loading available rooms...</p> : <form onSubmit={(event) => void submit(event)}>{data?.requirements.map((requirement) => <fieldset key={requirement.reservationLineId}><legend>{requirement.roomType.name} × {requirement.requiredRooms}</legend>{Array.from({ length: requirement.requiredRooms }, (_, index) => <label key={index}>Room {index + 1}<select required value={selected[requirement.reservationLineId]?.[index] ?? ''} onChange={(event) => choose(requirement.reservationLineId, index, event.target.value)}><option value="">Select available room</option>{requirement.availableRooms.map((room) => <option key={room.id} value={room.id}>{room.roomNumber}{room.floor ? ` · Floor ${room.floor}` : ''}{room.wing ? ` · ${room.wing}` : ''}</option>)}</select></label>)}</fieldset>)}{error && <p className="arrivalDetailsActionError" role="alert">{error}</p>}<footer><button className="smallBtn secondary" type="button" onClick={onClose}>Cancel</button><button className="smallBtn" type="submit" disabled={busy}>{busy ? 'Checking in...' : 'Confirm Check-In'}</button></footer></form>}</section></div>;
}
