'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { apiRequest } from '../lib/api';

type Guest = { id: string; displayName: string; mobile?: string | null; email?: string | null; vipLevel?: string | null; blacklisted: boolean; metrics: { completedStays: number; repeatGuest: boolean; roomNights: number; grossRevenue: number } };
type Detail = Guest & { gstin?: string | null; preferredLanguage?: string | null; preferences?: Record<string, unknown> | null; metrics: Guest['metrics'] & { verifiedPayments: number; lastStay?: string | null; nextStay?: string | null }; stays: { reference: string; checkIn: string; checkOut: string; stayStatus: string; hotel: { name: string }; roomTypes: string[] }[]; notes: { id: string; category: string; visibility: string; note: string; createdAt: string }[] };

const money = (value: number) => `INR ${Number(value ?? 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;
const date = (value?: string | null) => value ? new Date(value).toLocaleDateString('en-IN') : '—';

export function GuestListData() {
  const [rows, setRows] = useState<Guest[]>([]); const [search, setSearch] = useState(''); const [repeat, setRepeat] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  async function load() { setLoading(true); setError(''); try { const params = new URLSearchParams(); if (search.trim()) params.set('search', search.trim()); if (repeat) params.set('repeat', 'true'); setRows(await apiRequest<Guest[]>(`/guests?${params}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load guests.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [repeat]);
  return <section className="panel"><div className="sectionHead"><div><span>CRM</span><h2>Guest profiles</h2><p>Identity-safe history, repeat stays, and operational preferences.</p></div></div><form className="inlineForm" onSubmit={(event) => { event.preventDefault(); void load(); }}><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, mobile or email" /><label><input type="checkbox" checked={repeat} onChange={(event) => setRepeat(event.target.checked)} /> Repeat guests only</label><button className="btn" type="submit">Search</button></form>{error && <p className="error" role="alert">{error}</p>}{loading ? <p>Loading guest profiles…</p> : rows.length ? <div className="tableWrap"><table><thead><tr><th>Guest</th><th>Contact</th><th>Completed stays</th><th>Room nights</th><th>Lifetime gross</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.displayName}</strong>{row.metrics.repeatGuest && <small className="status ok"> Returning guest</small>}</td><td>{row.mobile || '—'}<br />{row.email || '—'}</td><td>{row.metrics.completedStays}</td><td>{row.metrics.roomNights}</td><td>{money(row.metrics.grossRevenue)}</td><td><Link className="smallBtn" href={`/admin/guests/${row.id}`}>Open profile</Link></td></tr>)}</tbody></table></div> : <div className="emptyState"><strong>No guest profiles found</strong><span>Profiles are linked only by exact normalized mobile or email.</span></div>}</section>;
}

export function GuestProfileData({ id }: { id: string }) {
  const [profile, setProfile] = useState<Detail | null>(null); const [error, setError] = useState('');
  useEffect(() => { apiRequest<Detail>(`/guests/${encodeURIComponent(id)}`).then(setProfile).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load guest profile.')); }, [id]);
  if (error) return <p className="error" role="alert">{error}</p>; if (!profile) return <p>Loading guest profile…</p>;
  return <div className="guestProfileWorkspace"><div className="pageTitle"><div><span>Guest CRM</span><h1>{profile.displayName}</h1><p>{profile.mobile || 'No mobile'} · {profile.email || 'No email'}</p></div><Link className="btn secondary" href="/admin/guests">Back to guests</Link></div><div className="metrics"><div><span>Completed stays</span><strong>{profile.metrics.completedStays}</strong></div><div><span>Repeat guest</span><strong>{profile.metrics.repeatGuest ? 'Yes' : 'No'}</strong></div><div><span>Room nights</span><strong>{profile.metrics.roomNights}</strong></div><div><span>Lifetime gross</span><strong>{money(profile.metrics.grossRevenue)}</strong></div><div><span>Verified payments</span><strong>{money(profile.metrics.verifiedPayments)}</strong></div></div><section className="panel"><div className="sectionHead"><div><span>Stay history</span><h2>Authoritative reservation history</h2></div></div>{profile.metrics.nextStay && <p className="notice">Next stay: {date(profile.metrics.nextStay)} · returning guest badge is available to front office.</p>}<div className="tableWrap"><table><thead><tr><th>Reference</th><th>Hotel</th><th>Stay</th><th>Status</th><th>Room nights</th></tr></thead><tbody>{profile.stays.map((stay) => <tr key={stay.reference}><td>{stay.reference}</td><td>{stay.hotel.name}</td><td>{date(stay.checkIn)} → {date(stay.checkOut)}</td><td>{stay.stayStatus}</td><td>{stay.roomTypes.join(', ')}</td></tr>)}</tbody></table></div></section><section className="panel"><div className="sectionHead"><div><span>Operational context</span><h2>Scoped notes</h2></div></div>{profile.notes.length ? profile.notes.map((note) => <p className="notice" key={note.id}><strong>{note.category}</strong> · {note.visibility} · {note.note}</p>) : <div className="emptyState"><strong>No notes</strong><span>Only authorised, visibility-scoped notes appear here.</span></div>}</section></div>;
}
