'use client';

import { useEffect, useMemo, useState } from 'react';
import { apiRequest } from '../lib/api';
import { useAdminProfile } from './AdminData';

type Hotel = { id: string; name: string; timezoneName?: string };
type ForecastRow = { stayDate: string; available: boolean; sellableRooms: number | null; bookedRooms: number | null; heldRooms: number | null; roomRevenue: number | null; adr: number | null; occupancyPercent: number | null; projectedBookedRooms: number | null; demandSignal: string; signals: string[]; pickup: Record<string, number | null>; pace: Record<string, number | null> };
type Forecast = { hotel: Hotel & { timezoneName: string }; observationDate: string; from: string; to: string; pickupWindows: number[]; summary: { availableDateCount: number; requestedDateCount: number; sellableRooms: number; bookedRooms: number; heldRooms: number; roomRevenue: number; occupancyPercent: number | null }; roomTypes: { roomTypeId: string; roomType: string; sellableRooms: number; bookedRooms: number; heldRooms: number; roomRevenue: number; adr: number }[]; rows: ForecastRow[] };

const dateInZone = (timezone: string, value = new Date()) => { const parts = new Intl.DateTimeFormat('en-CA', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(value); const values = Object.fromEntries(parts.filter((part) => part.type !== 'literal').map((part) => [part.type, part.value])); return `${values.year}-${values.month}-${values.day}`; };
const shiftDate = (value: string, days: number) => { const date = new Date(`${value}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); };
const money = (value: number | null) => value === null ? 'Unavailable' : `INR ${Number(value).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export function RevenueForecast() {
  const { profile } = useAdminProfile();
  const canView = ['SUPER_ADMIN', 'CORPORATE_ADMIN', 'ADMIN'].includes(profile?.role ?? '');
  const [hotels, setHotels] = useState<Hotel[]>([]); const [hotelId, setHotelId] = useState(''); const [observationDate, setObservationDate] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const [data, setData] = useState<Forecast | null>(null); const [loading, setLoading] = useState(false); const [capturing, setCapturing] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');

  useEffect(() => { if (!canView) return; apiRequest<Hotel[]>('/hotels').then((items) => { setHotels(items); const first = items[0]; if (first) { const today = dateInZone(first.timezoneName ?? 'Asia/Kolkata'); setHotelId(first.id); setObservationDate(today); setFrom(today); setTo(shiftDate(today, 14)); } }).catch((reason: Error) => setError(reason.message)); }, [canView]);
  const query = useMemo(() => new URLSearchParams({ hotelId, observationDate, from, to, horizon: '30', pickupWindows: '1,3,7,14,30' }).toString(), [hotelId, observationDate, from, to]);
  useEffect(() => { if (!canView || !hotelId || !observationDate || !from || !to) return; setLoading(true); setError(''); apiRequest<Forecast>(`/revenue-forecast?${query}`).then(setData).catch((reason: Error) => { setData(null); setError(reason.message); }).finally(() => setLoading(false)); }, [canView, hotelId, observationDate, from, to, query]);
  const changeHotel = (value: string) => { const hotel = hotels.find((item) => item.id === value); setHotelId(value); if (hotel) { const today = dateInZone(hotel.timezoneName ?? 'Asia/Kolkata'); setObservationDate(today); setFrom(today); setTo(shiftDate(today, 14)); } };
  const capture = async () => { setCapturing(true); setError(''); setMessage(''); try { const result = await apiRequest<{ created: number; existing: number }>('/revenue-forecast/snapshots', { method: 'POST', body: JSON.stringify({ hotelId, observationDate, horizon: 30 }) }); setMessage(`Snapshot capture complete: ${result.created} new row(s), ${result.existing} already captured.`); const fresh = await apiRequest<Forecast>(`/revenue-forecast?${query}`); setData(fresh); } catch (reason) { setError((reason as Error).message); } finally { setCapturing(false); } };
  if (!canView) return <section className="pageSection"><p className="hint">Revenue Forecast access is limited to management roles.</p></section>;
  return <section className="pageSection revenueForecastPage">
    <header className="pageTitle"><div><span>Revenue intelligence</span><h1>Revenue Forecast</h1><p>Immutable on-the-books snapshots, pickup, pace, and transparent demand signals for planning. This page never changes rates or writes to external channels.</p></div></header>
    <section className="panel revenueForecastFilters"><div className="managementFilterGrid"><label>Hotel<select value={hotelId} onChange={(event) => changeHotel(event.target.value)} disabled={profile?.role === 'ADMIN'}>{hotels.map((hotel) => <option key={hotel.id} value={hotel.id}>{hotel.name}</option>)}</select></label><label>Observation date<input type="date" value={observationDate} onChange={(event) => setObservationDate(event.target.value)} /></label><label>Stay from<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>Stay to<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label></div><div className="formActions"><button className="smallBtn" type="button" onClick={() => void capture()} disabled={capturing || loading}>{capturing ? 'Capturing…' : 'Capture snapshot'}</button><span className="hint">Capture is idempotent and records the current inventory state.</span></div></section>
    {loading && <p className="loading">Loading forecast…</p>}{error && <p className="error" role="alert">{error}</p>}{message && <p className="notice" role="status">{message}</p>}
    {data && <>
      <section className="revenueForecastSummary"><div><strong>{data.summary.availableDateCount}/{data.summary.requestedDateCount}</strong><span>Dates with snapshots</span></div><div><strong>{data.summary.bookedRooms}</strong><span>Booked room nights</span></div><div><strong>{data.summary.heldRooms}</strong><span>Held rooms</span></div><div><strong>{data.summary.occupancyPercent === null ? 'Unavailable' : `${data.summary.occupancyPercent}%`}</strong><span>OTB occupancy</span></div><div><strong>{money(data.summary.roomRevenue)}</strong><span>OTB room revenue</span></div></section>
      {data.summary.availableDateCount < data.summary.requestedDateCount && <p className="notice">Some dates are unavailable because no immutable snapshot exists for the selected observation date. Pickup and pace stay unavailable until both snapshots exist.</p>}
      <section className="panel"><div className="listToolbar"><div><span>Booking curve</span><h2>OTB, pickup &amp; pace</h2><p>Pickup is the change in booked rooms between immutable snapshots. Forecast is OTB plus positive 7-day pickup and is intentionally transparent.</p></div><span className="status ok">Observation {data.observationDate}</span></div><div className="tableScroll"><table><thead><tr><th>Stay date</th><th>Sellable</th><th>OTB</th><th>Held</th><th>Occupancy</th><th>ADR</th>{data.pickupWindows.map((window) => <th key={window}>Pickup {window}d</th>)}<th>Projected OTB</th><th>Demand</th></tr></thead><tbody>{data.rows.map((row) => <tr key={row.stayDate}><td><b>{row.stayDate}</b></td><td>{row.sellableRooms ?? 'Unavailable'}</td><td>{row.bookedRooms ?? 'Unavailable'}</td><td>{row.heldRooms ?? 'Unavailable'}</td><td>{row.occupancyPercent === null ? 'Unavailable' : `${row.occupancyPercent}%`}</td><td>{money(row.adr)}</td>{data.pickupWindows.map((window) => <td key={window}>{row.pickup[String(window)] === null ? 'Unavailable' : `${row.pickup[String(window)]} · ${row.pace[String(window)]}/day`}</td>)}<td>{row.projectedBookedRooms ?? 'Unavailable'}</td><td><span className={`status ${row.demandSignal === 'HIGH' ? 'warn' : row.demandSignal === 'UNAVAILABLE' ? '' : 'ok'}`}>{row.demandSignal}</span><small className="forecastSignalText">{row.signals[0]}</small></td></tr>)}{!data.rows.length && <tr><td colSpan={10}>No stay dates selected.</td></tr>}</tbody></table></div></section>
      <section className="panel"><div className="listToolbar"><div><span>Current snapshot</span><h2>Room type breakdown</h2></div></div><div className="tableScroll"><table><thead><tr><th>Room type</th><th>Sellable</th><th>Booked</th><th>Held</th><th>Revenue</th><th>ADR</th></tr></thead><tbody>{data.roomTypes.map((row) => <tr key={row.roomTypeId}><td>{row.roomType}</td><td>{row.sellableRooms}</td><td>{row.bookedRooms}</td><td>{row.heldRooms}</td><td>{money(row.roomRevenue)}</td><td>{money(row.adr)}</td></tr>)}{!data.roomTypes.length && <tr><td colSpan={6} className="empty">No room-type snapshot rows are available.</td></tr>}</tbody></table></div></section>
    </>}
  </section>;
}
