'use client';

import { useEffect, useMemo, useState } from 'react';
import { apiRequest } from '../lib/api';

type Assignment = { id: string; room: { id: string; roomNumber: string; roomType: { id: string; name: string } } };
type Room = { id: string; roomNumber: string; floor: string | null; wing: string | null; status: string; roomType: { id: string; name: string } };

export function RoomChangeDialog({ reference, hotelId, assignments, onClose, onSuccess }: { reference: string; hotelId: string; assignments: Assignment[]; onClose: () => void; onSuccess: () => void }) {
  const [rooms, setRooms] = useState<Room[]>([]); const [assignmentId, setAssignmentId] = useState(assignments[0]?.id ?? ''); const [newRoomId, setNewRoomId] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const current = assignments.find((item) => item.id === assignmentId);
  const choices = useMemo(() => rooms.filter((room) => room.status === 'AVAILABLE' && room.roomType.id === current?.room.roomType.id), [rooms, current]);
  useEffect(() => { apiRequest<Room[]>(`/hotels/physical-rooms?hotelId=${encodeURIComponent(hotelId)}`).then(setRooms).catch((value) => setError(value instanceof Error ? value.message : 'Could not load replacement rooms.')); }, [hotelId]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!assignmentId || !newRoomId || reason.trim().length < 2) { setError('Select the room assignment, replacement room, and a reason.'); return; } setBusy(true); setError(''); try { await apiRequest(`/reservations/${encodeURIComponent(reference)}/room-change`, { method: 'POST', body: JSON.stringify({ assignmentId, newRoomId, reason: reason.trim() }) }); onSuccess(); } catch (value) { setError(value instanceof Error ? value.message : 'Could not change room.'); } finally { setBusy(false); } }
  return <div className="arrivalFolioDialogBackdrop" role="presentation"><section className="arrivalFolioDialog" role="dialog" aria-modal="true" aria-labelledby="room-change-title"><header><div><span className="eyebrow">Front Desk Operations</span><h3 id="room-change-title">Change Room</h3><p>{reference}</p></div><button className="uiModalClose" type="button" onClick={onClose} aria-label="Close room change">×</button></header><form onSubmit={(event) => void submit(event)}><label>Current assignment<select value={assignmentId} onChange={(event) => { setAssignmentId(event.target.value); setNewRoomId(''); }}>{assignments.map((item) => <option key={item.id} value={item.id}>{item.room.roomNumber} · {item.room.roomType.name}</option>)}</select></label><label>Replacement room<select required value={newRoomId} onChange={(event) => setNewRoomId(event.target.value)}><option value="">Select available room</option>{choices.map((room) => <option key={room.id} value={room.id}>{room.roomNumber}{room.floor ? ` · Floor ${room.floor}` : ''}{room.wing ? ` · ${room.wing}` : ''}</option>)}</select></label><label>Reason<textarea required minLength={2} maxLength={500} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="e.g. AC not working" /></label>{error && <p className="arrivalDetailsActionError" role="alert">{error}</p>}<footer><button className="smallBtn secondary" type="button" onClick={onClose}>Cancel</button><button className="smallBtn" type="submit" disabled={busy}>{busy ? 'Changing...' : 'Confirm Room Change'}</button></footer></form></section></div>;
}
