'use client';

import { FormEvent, useEffect, useState } from 'react';
import { apiRequest } from '../lib/api';
import type { StaffProfile } from './StaffData';

type Stay = { reference: string; guestName: string; assignedRooms: { roomNumber: string }[] };
type Item = { id: string; name: string; type: string; unitPrice: number; taxRate: number };
type Folio = { reference: string; charges: unknown[] };

export function StaffServiceOrdersData() {
  const [profile, setProfile] = useState<StaffProfile | null>(null); const [stays, setStays] = useState<Stay[]>([]); const [items, setItems] = useState<Item[]>([]); const [reference, setReference] = useState(''); const [quantities, setQuantities] = useState<Record<string, string>>({}); const [review, setReview] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { Promise.all([apiRequest<StaffProfile>('/staff/me'), apiRequest<Stay[]>('/staff/stays'), apiRequest<Item[]>('/staff/service-items')]).then(([me, guests, catalog]) => { setProfile(me); setStays(guests); setItems(catalog); setReference(guests[0]?.reference ?? ''); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load service order context.')); }, []);
  const selected = items.filter((item) => Number(quantities[item.id] ?? 0) > 0); const estimate = selected.reduce((sum, item) => sum + Number(quantities[item.id]) * item.unitPrice * (1 + item.taxRate / 100), 0); const stay = stays.find((row) => row.reference === reference);
  async function post(event?: FormEvent) { event?.preventDefault(); if (!stay || !selected.length || !profile) return; setBusy(true); setError(''); try { await apiRequest<Folio>(`/staff/stays/${encodeURIComponent(stay.reference)}/service-orders`, { method: 'POST', body: JSON.stringify({ department: profile.department, idempotencyKey: `PWA-${crypto.randomUUID()}`, lines: selected.map((item) => ({ serviceItemId: item.id, quantity: Number(quantities[item.id]) })) }) }); setMessage('Service order posted to the guest folio.'); setQuantities({}); setReview(false); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not post service order.'); } finally { setBusy(false); } }
  return <section className="staffContent"><div className="staffWelcome"><span className="staffEyebrow">Guest services</span><h1>{profile?.department === 'HOUSEKEEPING' ? 'Laundry posting' : 'F&B / Room Service'}</h1><p>Prices are loaded from the hotel service-item master and posted through the existing guest folio.</p></div>{error && <p className="staffError" role="alert">{error}</p>}<label className="staffSearch">Guest / room<select value={reference} onChange={(event) => setReference(event.target.value)}>{stays.map((row) => <option key={row.reference} value={row.reference}>{row.assignedRooms.map((room) => room.roomNumber).join(', ') || 'Unassigned'} · {row.guestName} · {row.reference}</option>)}</select></label>{review ? <div className="staffConfirm"><p>Post {selected.map((item) => `${item.name} × ${quantities[item.id]}`).join(', ')} for estimated total <strong>INR {estimate.toFixed(2)}</strong>?</p><button className="staffButton secondary" type="button" onClick={() => setReview(false)}>Back</button><button className="staffButton" type="button" disabled={busy} onClick={() => void post()}>{busy ? 'Posting…' : 'Confirm Post to Room'}</button></div> : <><div className="staffChargeList">{items.map((item) => <label className="staffChargeCard" key={item.id}><div><strong>{item.name}</strong><span>{item.type} · INR {item.unitPrice.toFixed(2)} + {item.taxRate}% tax</span></div><input aria-label={`Quantity ${item.name}`} type="number" min="0" step="1" value={quantities[item.id] ?? ''} onChange={(event) => setQuantities({ ...quantities, [item.id]: event.target.value })} /></label>)}</div><div className="staffTotal"><span>Estimated total</span><strong>INR {estimate.toFixed(2)}</strong></div><button className="staffButton full" type="button" disabled={!stay || !selected.length} onClick={() => setReview(true)}>Review service order</button></>}</section>;
}
