'use client';

import { FormEvent, useState } from 'react';
import { apiRequest } from '../lib/api';

export function StaffLostFoundData() {
  const [form, setForm] = useState({ itemCategory: '', description: '', roomId: '', locationFound: '', notes: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { await apiRequest('/staff/lost-found', { method: 'POST', body: JSON.stringify({ type: 'FOUND', ...form, roomId: form.roomId || undefined }) }); setMessage('Found item reported.'); setForm({ itemCategory: '', description: '', roomId: '', locationFound: '', notes: '' }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not report found item.'); } finally { setBusy(false); } }
  return <section className="staffContent"><div className="staffWelcome"><span className="staffEyebrow">Housekeeping operations</span><h1>Report Found Item</h1><p>Report what was found and where. Guest ownership is never assumed automatically.</p></div>{error && <p className="staffError" role="alert">{error}</p>}{message && <p className="staffSuccess" role="status">{message}</p>}<form className="staffSheet" onSubmit={submit}><label>Item category<input required value={form.itemCategory} onChange={(event) => setForm({ ...form, itemCategory: event.target.value })} placeholder="Watch, wallet, clothing" /></label><label>Description<textarea required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label>Room ID<input value={form.roomId} onChange={(event) => setForm({ ...form, roomId: event.target.value })} placeholder="Optional room ID" /></label><label>Location found<input value={form.locationFound} onChange={(event) => setForm({ ...form, locationFound: event.target.value })} placeholder="Bedside table" /></label><label>Notes<input value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label><button className="staffButton full" disabled={busy}>{busy ? 'Reporting…' : 'Report found item'}</button></form></section>;
}
