'use client';

import { useEffect, useState } from 'react';
import { AdminLayout } from '../../../components/Shell';
import { apiRequest } from '../../../lib/api';

type Hotel = { id: string; name: string };
type Promotion = { id: string; code?: string | null; name: string; discountType: 'PERCENT' | 'FIXED'; discountValue: number | string; active: boolean };

export default function PromotionsPage() {
  const [hotels, setHotels] = useState<Hotel[]>([]); const [hotelId, setHotelId] = useState(''); const [promotions, setPromotions] = useState<Promotion[]>([]);
  const [form, setForm] = useState({ code: '', name: '', discountType: 'PERCENT', discountValue: '', minNights: '' }); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function load(id = hotelId) { if (!id) return; setPromotions(await apiRequest<Promotion[]>(`/hotels/${id}/promotions`)); }
  useEffect(() => { apiRequest<Hotel[]>('/hotels').then((items) => { setHotels(items); if (items[0]) { setHotelId(items[0].id); void load(items[0].id); } }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load hotels')); }, []);
  async function create(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { await apiRequest(`/hotels/${hotelId}/promotions`, { method: 'POST', body: JSON.stringify({ code: form.code || undefined, name: form.name, discountType: form.discountType, discountValue: Number(form.discountValue), minNights: form.minNights ? Number(form.minNights) : undefined }) }); setForm({ code: '', name: '', discountType: 'PERCENT', discountValue: '', minNights: '' }); setMessage('Promotion created. One best eligible promotion is applied at quote time.'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not create promotion'); } finally { setBusy(false); } }
  async function disable(id: string) { setBusy(true); try { await apiRequest(`/hotels/promotions/${id}`, { method: 'PATCH', body: JSON.stringify({ active: false }) }); await load(); setMessage('Promotion disabled.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not update promotion'); } finally { setBusy(false); } }
  return <AdminLayout title="Promotions"><section className="pageSection"><header className="pageTitle"><div><span>Commercial controls</span><h1>Promotions</h1><p>Promotions are stored separately from base rates and the best eligible offer wins.</p></div></header>{error && <p className="error" role="alert">{error}</p>}{message && <p className="notice" role="status">{message}</p>}<section className="panel"><div className="rangeToolbar"><label>Hotel<select value={hotelId} onChange={(event) => { setHotelId(event.target.value); void load(event.target.value); }}><option value="">Select hotel</option>{hotels.map((hotel) => <option key={hotel.id} value={hotel.id}>{hotel.name}</option>)}</select></label></div><form className="rangeToolbar" onSubmit={create}><label>Code<input value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} placeholder="Optional" /></label><label>Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Discount type<select value={form.discountType} onChange={(event) => setForm({ ...form, discountType: event.target.value })}><option value="PERCENT">Percent</option><option value="FIXED">Fixed INR</option></select></label><label>Value<input required type="number" min="0" step="0.01" value={form.discountValue} onChange={(event) => setForm({ ...form, discountValue: event.target.value })} /></label><label>Minimum nights<input type="number" min="1" value={form.minNights} onChange={(event) => setForm({ ...form, minNights: event.target.value })} placeholder="Optional" /></label><button className="btn" disabled={busy || !hotelId}>Create promotion</button></form></section><section className="panel"><h2>Configured promotions</h2>{promotions.length ? <div className="dataTableWrap"><table className="dataTable"><thead><tr><th>Name</th><th>Code</th><th>Discount</th><th>Status</th><th>Action</th></tr></thead><tbody>{promotions.map((promotion) => <tr key={promotion.id}><td>{promotion.name}</td><td>{promotion.code || '—'}</td><td>{promotion.discountType === 'PERCENT' ? `${promotion.discountValue}%` : `INR ${promotion.discountValue}`}</td><td><span className={`status ${promotion.active ? 'ok' : 'err'}`}>{promotion.active ? 'Active' : 'Disabled'}</span></td><td>{promotion.active && <button className="smallBtn" type="button" disabled={busy} onClick={() => void disable(promotion.id)}>Disable</button>}</td></tr>)}</tbody></table></div> : <p className="empty">No promotions configured for this hotel.</p>}</section></section></AdminLayout>;
}
