'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { AdminLayout } from '../../../../../components/Shell';
import { apiRequest } from '../../../../../lib/api';

type OccupancyKey = 'single' | 'double' | 'triple' | 'quad' | 'extrabed' | 'extraadult' | 'extrachild' | 'extraadult2' | 'extrachild2' | 'extraadult3' | 'extrachild3' | 'extrainfant';
type Rate = { id: string; date: string; amount: string | number; taxAmount: string | number; occupancyPrices?: Partial<Record<OccupancyKey, string | number>>; cta: boolean; ctd: boolean };
const occupancyFields: { key: OccupancyKey; label: string }[] = [{ key: 'single', label: 'Single (INR)' }, { key: 'double', label: 'Double (INR)' }, { key: 'triple', label: 'Triple (INR)' }, { key: 'quad', label: 'Quad (INR)' }, { key: 'extrabed', label: 'Extra bed (INR)' }, { key: 'extraadult', label: 'Extra adult (INR)' }, { key: 'extrachild', label: 'Extra child (INR)' }, { key: 'extraadult2', label: 'Extra adult 2 (INR)' }, { key: 'extrachild2', label: 'Extra child 2 (INR)' }, { key: 'extraadult3', label: 'Extra adult 3 (INR)' }, { key: 'extrachild3', label: 'Extra child 3 (INR)' }, { key: 'extrainfant', label: 'Extra infant (INR)' }];
type Plan = { id: string; code: string; name: string; mealPlan: string; active: boolean; rates: Rate[] };
type Room = { id: string; code: string; name: string; description?: string | null; maxAdults: number; maxChildren: number; maxOccupancy: number; active: boolean; ratePlans: Plan[]; inventory: { id: string; date: string; available: number; held: number; sold: number; stopSell: boolean }[] };
type Catalog = { id: string; name: string; rooms: Room[] };

function dateKeys(start: string, end: string) {
  const today = new Date().toISOString().slice(0, 10);
  if (!start || !end || start < today || end < today || start > end) return [] as string[];
  const result: string[] = [];
  const cursor = new Date(`${start}T00:00:00.000Z`);
  const last = new Date(`${end}T00:00:00.000Z`);
  while (cursor <= last && result.length < 370) {
    result.push(cursor.toISOString().slice(0, 10));
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  return result;
}

export default function CatalogPage() {
  const params = useParams<{ id: string }>();
  const hotelId = params.id;
  const [catalog, setCatalog] = useState<Catalog | null>(null);
  const [room, setRoom] = useState({ code: '', name: '', description: '', maxAdults: 2, maxChildren: 1, maxOccupancy: 3 });
  const [plan, setPlan] = useState({ roomTypeId: '', code: '', name: '', mealPlan: 'CP' });
  const [day, setDay] = useState({ roomTypeId: '', ratePlanId: '', date: '', available: 0, amount: 0, taxAmount: 0, stopSell: false });
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [expandedRoom, setExpandedRoom] = useState<string | null>(null);
  const [rangeRoomId, setRangeRoomId] = useState(''); const [rangeRatePlanId, setRangeRatePlanId] = useState(''); const [rangeStart, setRangeStart] = useState(''); const [rangeEnd, setRangeEnd] = useState(''); const [rangeAvailable, setRangeAvailable] = useState(0); const [rangeAmount, setRangeAmount] = useState(0); const [rangeTaxAmount, setRangeTaxAmount] = useState(0); const [rangeOccupancy, setRangeOccupancy] = useState({ single: 0, double: 0, triple: 0, quad: 0, extrabed: 0, extraadult: 0, extrachild: 0, extraadult2: 0, extrachild2: 0, extraadult3: 0, extrachild3: 0, extrainfant: 0 }); const [viewedRange, setViewedRange] = useState<{ start: string; end: string } | null>(null);
  async function load(startDate?: string, endDate?: string) { try { const query = startDate && endDate ? `?startDate=${encodeURIComponent(startDate)}&endDate=${encodeURIComponent(endDate)}` : ''; setCatalog(await apiRequest<Catalog>(`/hotels/${hotelId}/catalog${query}`)); setViewedRange(startDate && endDate ? { start: startDate, end: endDate } : null); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load catalogue'); } }
  useEffect(() => { void load(); }, [hotelId]);
  const rooms = catalog?.rooms ?? [];
  const rangeRoom = rooms.find((item) => item.id === rangeRoomId) ?? rooms[0];
  const rangePlans = rangeRoom?.ratePlans ?? [];
  const rangePlan = rangePlans.find((item) => item.id === rangeRatePlanId) ?? rangePlans[0];
  useEffect(() => { if (!rangeRoomId && rooms[0]) setRangeRoomId(rooms[0].id); }, [rooms, rangeRoomId]);
  useEffect(() => { if (rangeRoom && !rangePlans.some((item) => item.id === rangeRatePlanId)) setRangeRatePlanId(rangePlans[0]?.id ?? ''); }, [rangeRoom, rangePlans, rangeRatePlanId]);
  async function save(path: string, body: unknown, refreshStart?: string, refreshEnd?: string) { setBusy(true); setError(''); setMessage(''); try { await apiRequest(path, { method: 'POST', body: JSON.stringify(body) }); await load(refreshStart, refreshEnd); setMessage('Saved successfully.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save'); } finally { setBusy(false); } }
  function submitRoom(event: FormEvent) { event.preventDefault(); void save(`/hotels/${hotelId}/rooms`, room); }
  function submitPlan(event: FormEvent) { event.preventDefault(); void save(`/hotels/rooms/${plan.roomTypeId}/rate-plans`, { code: plan.code, name: plan.name, mealPlan: plan.mealPlan }); }
  function submitInventory(event: FormEvent) { event.preventDefault(); void save(`/hotels/rooms/${day.roomTypeId}/inventory`, { days: [{ date: day.date, available: Number(day.available), stopSell: day.stopSell }] }); }
  function submitRate(event: FormEvent) { event.preventDefault(); void save(`/hotels/rate-plans/${day.ratePlanId}/rates`, { days: [{ date: day.date, amount: Number(day.amount), taxAmount: Number(day.taxAmount) }] }); }
  function saveRange(kind: 'inventory' | 'rate') {
    const dates = dateKeys(rangeStart, rangeEnd);
    if (!rangeRoom || !dates.length) { setError('Select a room and a valid start/end date range.'); return; }
    if (kind === 'rate' && !rangePlan) { setError('Select a rate plan.'); return; }
    if (kind === 'inventory') void save(`/hotels/rooms/${rangeRoom.id}/inventory`, { days: dates.map((date) => ({ date, available: Number(rangeAvailable), stopSell: false })) }, rangeStart, rangeEnd);
    else void save(`/hotels/rate-plans/${rangePlan!.id}/rates`, { days: dates.map((date) => ({ date, amount: Number(rangeAmount), taxAmount: Number(rangeTaxAmount), occupancyPrices: rangeOccupancy })) }, rangeStart, rangeEnd);
  }
  const rangeDates = dateKeys(rangeStart, rangeEnd);
  return <AdminLayout title={catalog ? catalog.name : 'Hotel catalog'}><p><Link href="/admin/hotels">Back to hotels</Link></p>{error && <p className="error" role="alert">{error}</p>}{message && <p className="notice" role="status">{message}</p>}
    <div className="catalogGrid"><form className="formCard" onSubmit={submitRoom}><h2>Add room type</h2><label>Room code<input value={room.code} onChange={(e) => setRoom({ ...room, code: e.target.value })} placeholder="DLX" required /></label><label>Room name<input value={room.name} onChange={(e) => setRoom({ ...room, name: e.target.value })} placeholder="Deluxe Valley Room" required /></label><label>Description<textarea value={room.description} onChange={(e) => setRoom({ ...room, description: e.target.value })} /></label><div className="three"><label>Adults<input type="number" min="1" value={room.maxAdults} onChange={(e) => setRoom({ ...room, maxAdults: Number(e.target.value) })} /></label><label>Children<input type="number" min="0" value={room.maxChildren} onChange={(e) => setRoom({ ...room, maxChildren: Number(e.target.value) })} /></label><label>Occupancy<input type="number" min="1" value={room.maxOccupancy} onChange={(e) => setRoom({ ...room, maxOccupancy: Number(e.target.value) })} /></label></div><button className="btn" disabled={busy}>Add room</button></form>
      <form className="formCard" onSubmit={submitPlan}><h2>Add rate plan</h2><label>Room<select value={plan.roomTypeId} onChange={(e) => setPlan({ ...plan, roomTypeId: e.target.value })} required><option value="">Select room</option>{rooms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Plan code<input value={plan.code} onChange={(e) => setPlan({ ...plan, code: e.target.value })} placeholder="MAP" required /></label><label>Plan name<input value={plan.name} onChange={(e) => setPlan({ ...plan, name: e.target.value })} placeholder="MAP - Breakfast & Dinner" required /></label><label>Meal plan<select value={plan.mealPlan} onChange={(e) => setPlan({ ...plan, mealPlan: e.target.value })}><option>EP</option><option>CP</option><option>MAP</option><option>AP</option></select></label><button className="btn" disabled={busy}>Add rate plan</button></form>
      <form className="formCard" onSubmit={submitInventory}><h2>Save inventory</h2><label>Room<select value={day.roomTypeId} onChange={(e) => setDay({ ...day, roomTypeId: e.target.value })} required><option value="">Select room</option>{rooms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Date<input type="date" value={day.date} onChange={(e) => setDay({ ...day, date: e.target.value })} required /></label><label>Available rooms<input type="number" min="0" value={day.available} onChange={(e) => setDay({ ...day, available: Number(e.target.value) })} required /></label><label className="checkLabel"><input type="checkbox" checked={day.stopSell} onChange={(e) => setDay({ ...day, stopSell: e.target.checked })} /> Stop sell</label><button className="btn" disabled={busy}>Save inventory</button></form>
      <form className="formCard" onSubmit={submitRate}><h2>Save daily rate</h2><label>Rate plan<select value={day.ratePlanId} onChange={(e) => setDay({ ...day, ratePlanId: e.target.value })} required><option value="">Select rate plan</option>{rooms.flatMap((item) => item.ratePlans.map((itemPlan) => <option key={itemPlan.id} value={itemPlan.id}>{item.name}  - {itemPlan.name}</option>))}</select></label><label>Date<input type="date" value={day.date} onChange={(e) => setDay({ ...day, date: e.target.value })} required /></label><div className="two"><label>Base amount<input type="number" min="0" step="0.01" value={day.amount} onChange={(e) => setDay({ ...day, amount: Number(e.target.value) })} required /></label><label>Tax amount<input type="number" min="0" step="0.01" value={day.taxAmount} onChange={(e) => setDay({ ...day, taxAmount: Number(e.target.value) })} /></label></div><button className="btn" disabled={busy}>Save rate</button></form></div>
    <section className="panel rangeEditor"><h2>Range price book</h2><p className="mutedText">Select a room, rate plan, and date range to save the same inventory or rate across every date, then review the date grid below.</p><div className="rangeToolbar"><label>Room<select value={rangeRoomId} onChange={(e) => setRangeRoomId(e.target.value)}><option value="">Select room</option>{rooms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Rate plan<select value={rangeRatePlanId} onChange={(e) => setRangeRatePlanId(e.target.value)}><option value="">Select rate plan</option>{rangePlans.map((item) => <option key={item.id} value={item.id}>{item.name} - {item.mealPlan}</option>)}</select></label><label>Start date<input type="date" value={rangeStart} onChange={(e) => setRangeStart(e.target.value)} onInput={(e) => { const value = e.currentTarget.value; setRangeStart(value); }} /></label><label>End date<input type="date" value={rangeEnd} onChange={(e) => setRangeEnd(e.target.value)} onInput={(e) => { const value = e.currentTarget.value; setRangeEnd(value); }} /></label></div><div className="rangeSaveGrid"><div><label>Available rooms<input type="number" min="0" value={rangeAvailable} onChange={(e) => setRangeAvailable(Number(e.target.value))} /></label><button className="btn" disabled={busy || !rangeDates.length} onClick={() => saveRange('inventory')}>Save inventory for range</button></div><div><div className="occupancyGrid">{occupancyFields.map((field) => <label key={field.key}>{field.label}<input type="number" min="0" step="0.01" value={rangeOccupancy[field.key]} onChange={(e) => setRangeOccupancy((current) => ({ ...current, [field.key]: Number(e.target.value) }))} /></label>)}</div><label>Base amount<input type="number" min="0" step="0.01" value={rangeAmount} onChange={(e) => setRangeAmount(Number(e.target.value))} /></label><label>Tax amount<input type="number" min="0" step="0.01" value={rangeTaxAmount} onChange={(e) => setRangeTaxAmount(Number(e.target.value))} /></label><button className="btn" disabled={busy || !rangeDates.length || !rangePlan} onClick={() => saveRange('rate')}>Save rate for range</button></div></div>{rangeDates.length > 0 && <div className="tableScroll rangePreview"><h3>{rangeRoom?.name ?? 'Room'} - {rangePlan?.name ?? 'Rate plan'} - {rangeDates.length} dates</h3><table><thead><tr><th>Date</th><th>Inventory</th><th>Rate</th><th>Tax</th><th>Stop sell</th></tr></thead><tbody>{rangeDates.map((date) => { const inv = rangeRoom?.inventory.find((item) => item.date.slice(0, 10) === date); const rate = rangePlan?.rates.find((item) => item.date.slice(0, 10) === date); return <tr key={date}><td>{date}</td><td>{inv?.available ?? ' - '}</td><td>{rate ? `INR ${Number(rate.amount).toFixed(2)}` : ' - '}</td><td>{rate ? `INR ${Number(rate.taxAmount).toFixed(2)}` : ' - '}</td><td>{inv?.stopSell ? 'Yes' : 'Open'}</td></tr>; })}</tbody></table></div>}</section>
    <section className="panel catalogSummary"><h2>Configured catalogue</h2>{!catalog ? <p className="loading">Loading catalogue - </p> : !rooms.length ? <p className="empty">No room types configured yet.</p> : rooms.map((item) => <article className="catalogRoom" key={item.id}><div className="catalogRoomMain"><div><h3>{item.name} <small>({item.code})</small></h3><p>{item.description || 'No description'}  - {item.maxOccupancy}</p><b>{item.inventory.length} inventory rows</b>  - <b>{item.ratePlans.length} rate plans</b></div><div className="catalogRoomActions"><div>{item.ratePlans.map((itemPlan) => <span className="tag" key={itemPlan.id}>{itemPlan.code} | {itemPlan.rates.length} rates</span>)}</div><button className="smallBtn" onClick={() => setExpandedRoom(expandedRoom === item.id ? null : item.id)}>{expandedRoom === item.id ? 'Hide details' : 'View details'}</button></div></div>{expandedRoom === item.id && <div className="catalogDetails"><h4>Inventory by date</h4>{item.inventory.length ? <div className="tableScroll"><table><thead><tr><th>Date</th><th>Available</th><th>Held</th><th>Sold</th><th>Stop sell</th></tr></thead><tbody>{item.inventory.map((inventoryDay) => <tr key={inventoryDay.id}><td>{inventoryDay.date.slice(0, 10)}</td><td>{inventoryDay.available}</td><td>{inventoryDay.held}</td><td>{inventoryDay.sold}</td><td><span className={`status ${inventoryDay.stopSell ? 'err' : 'ok'}`}>{inventoryDay.stopSell ? 'Yes' : 'Open'}</span></td></tr>)}</tbody></table></div> : <p className="empty">No inventory rows.</p>}<h4>Rates by date</h4>{item.ratePlans.map((itemPlan) => <div key={itemPlan.id}><h5>{itemPlan.name}  - {itemPlan.mealPlan}</h5>{itemPlan.rates.length ? <div className="tableScroll"><table><thead><tr><th>Date</th><th>Base</th><th>Tax</th><th>CTA</th><th>CTD</th></tr></thead><tbody>{itemPlan.rates.map((rate) => <tr key={rate.id}><td>{rate.date.slice(0, 10)}</td><td>INR {Number(rate.amount).toFixed(2)}</td><td>INR {Number(rate.taxAmount).toFixed(2)}</td><td>{rate.cta ? 'Yes' : 'No'}</td><td>{rate.ctd ? 'Yes' : 'No'}</td></tr>)}</tbody></table></div> : <p className="empty">No rates configured.</p>}</div>)}</div>}</article>)}</section>
    <div className="rangeViewActions"><button className="smallBtn" disabled={busy || !rangeDates.length} onClick={() => void load(rangeStart, rangeEnd)}>Load saved range</button>{viewedRange && <span className="mutedText">Showing {viewedRange.start} to {viewedRange.end}</span>}</div>
  </AdminLayout>;
}






