import { BadRequestException, ForbiddenException } from '@nestjs/common';
import { CorporatePricingType, UserRole } from '@prisma/client';
import { CorporatesService } from './corporates.service';

describe('CorporatesService', () => {
  const p: any = { user: { findUnique: jest.fn() }, hotel: { findUnique: jest.fn() }, corporateAccount: { findMany: jest.fn(), findUnique: jest.fn(), create: jest.fn(), update: jest.fn() }, corporateAccountHotel: { upsert: jest.fn() }, corporateRateAgreement: { findFirst: jest.fn(), findUnique: jest.fn(), create: jest.fn(), update: jest.fn() }, ratePlan: { findFirst: jest.fn() }, reservation: { findMany: jest.fn() } };
  const audit = { log: jest.fn() } as any;
  const actor = (role: UserRole = UserRole.ADMIN, hotelId: string | null = 'hotel-a') => ({ id: 'user-1', role, staffHotelId: hotelId, staffDepartment: null, staffHotel: { id: hotelId, active: true } });
  let service: CorporatesService;
  beforeEach(() => { jest.clearAllMocks(); service = new CorporatesService(p, audit); p.user.findUnique.mockResolvedValue(actor()); p.hotel.findUnique.mockResolvedValue({ id: 'hotel-a', active: true }); p.corporateAccount.create.mockImplementation(async ({ data }: any) => ({ id: 'corp-1', ...data, hotels: [], rateAgreements: [] })); });

  it('creates a separate corporate account', async () => { const result = await service.create('user-1', { name: 'Synthetic Corp', creditDays: 30 }); expect(result.name).toBe('Synthetic Corp'); expect(audit.log).toHaveBeenCalledWith(expect.objectContaining({ action: 'CORPORATE_ACCOUNT_CREATED' })); });
  it('rejects hotel admins linking another hotel', async () => { await expect(service.linkHotel('user-1', 'corp-1', { hotelId: 'hotel-b' })).rejects.toBeInstanceOf(ForbiddenException); });
  it('allows global corporate admins to link multiple hotels', async () => { p.user.findUnique.mockResolvedValue(actor(UserRole.CORPORATE_ADMIN, null)); p.corporateAccount.findUnique.mockResolvedValue({ id: 'corp-1' }); p.corporateAccountHotel.upsert.mockResolvedValue({ corporateAccountId: 'corp-1', hotelId: 'hotel-b', active: true }); const result = await service.linkHotel('user-1', 'corp-1', { hotelId: 'hotel-b' }); expect(result.hotelId).toBe('hotel-b'); });
  it('validates and previews fixed corporate pricing', async () => { p.user.findUnique.mockResolvedValue(actor(UserRole.CORPORATE_ADMIN, null)); p.corporateAccount.findUnique.mockResolvedValue({ id: 'corp-1', hotels: [{ hotelId: 'hotel-a', active: true, hotel: { id: 'hotel-a', name: 'A' } }] }); p.corporateRateAgreement.findFirst.mockResolvedValue({ id: 'rate-1', pricingType: CorporatePricingType.FIXED, fixedRate: 900, discountPercent: null }); const result = await service.applyCorporateRate('user-1', 'corp-1', 'hotel-a', 'room-1', 'plan-1', '2026-10-01', 1200); expect(result.resolvedRate).toBe(900); expect(result.precedence).toContain('overrides'); });
  it('applies discount against the resolved public pre-promo rate', async () => { p.user.findUnique.mockResolvedValue(actor(UserRole.CORPORATE_ADMIN, null)); p.corporateAccount.findUnique.mockResolvedValue({ id: 'corp-1', hotels: [{ hotelId: 'hotel-a', active: true, hotel: { id: 'hotel-a', name: 'A' } }] }); p.corporateRateAgreement.findFirst.mockResolvedValue({ id: 'rate-1', pricingType: CorporatePricingType.DISCOUNT_PERCENT, fixedRate: null, discountPercent: 10 }); const result = await service.applyCorporateRate('user-1', 'corp-1', 'hotel-a', 'room-1', 'plan-1', '2026-10-01', 1000); expect(result.resolvedRate).toBe(900); });
  it('requires the configured field for each pricing type', async () => { p.user.findUnique.mockResolvedValue(actor(UserRole.CORPORATE_ADMIN, null)); p.corporateAccount.findUnique.mockResolvedValue({ id: 'corp-1', hotels: [{ hotelId: 'hotel-a', active: true, hotel: { id: 'hotel-a', name: 'A' } }] }); await expect(service.createRate('user-1', 'corp-1', { hotelId: 'hotel-a', roomTypeId: 'room-1', ratePlanId: 'plan-1', validFrom: '2026-10-01', validTo: '2026-10-02', pricingType: CorporatePricingType.FIXED })).rejects.toBeInstanceOf(BadRequestException); });
});
