import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { CorporatePricingType, UserRole } from '@prisma/client';
import { AuditService } from '../../common/audit.service';
import { PrismaService } from '../../common/prisma.service';
import { assertActorCanManageHotel, getActorScope, resolveRequestedHotel } from '../../common/role-scope';
import { CorporateCreateDto, CorporateLinkHotelDto, CorporateListQueryDto, CorporateRateDto } from './corporates.dto';

const MANAGEMENT: UserRole[] = [UserRole.SUPER_ADMIN, UserRole.CORPORATE_ADMIN, UserRole.ADMIN];
const readRoles: UserRole[] = [...MANAGEMENT, UserRole.RESERVATION, UserRole.ACCOUNTS];
const amount = (value: unknown) => Number(value ?? 0);

@Injectable()
export class CorporatesService {
  constructor(private readonly p: PrismaService, private readonly audit: AuditService) {}
  private async scope(userId: string, write = false) { const scope = await getActorScope(this.p, userId); const roles = write ? MANAGEMENT : readRoles; if (!roles.includes(scope.role)) throw new ForbiddenException('Corporate account access is not available to this account.'); return scope; }
  private async accountForHotel(userId: string, accountId: string, hotelId: string) { const scope = await this.scope(userId); if (!scope.isGlobal && scope.hotelId !== hotelId) throw new ForbiddenException('You cannot access another hotel.'); const account = await this.p.corporateAccount.findUnique({ where: { id: accountId }, include: { hotels: { where: { hotelId, active: true }, include: { hotel: { select: { id: true, name: true } } } } } }); if (!account || !account.hotels.length) throw new NotFoundException('Corporate account is not linked to this hotel.'); return account; }
  private view(row: any) { return { ...row, creditLimit: row.creditLimit === null ? null : amount(row.creditLimit), hotels: (row.hotels ?? []).map((link: any) => ({ ...link, creditLimitOverride: link.creditLimitOverride === null ? null : amount(link.creditLimitOverride), hotel: link.hotel })), rateAgreements: (row.rateAgreements ?? []).map((rate: any) => ({ ...rate, fixedRate: rate.fixedRate === null ? null : amount(rate.fixedRate), discountPercent: rate.discountPercent === null ? null : amount(rate.discountPercent) })) }; }
  async list(userId: string, query: CorporateListQueryDto) { const scope = await this.scope(userId); const hotelId = resolveRequestedHotel(scope, query.hotelId); const rows = await this.p.corporateAccount.findMany({ where: { active: query.active ?? undefined, name: query.search ? { contains: query.search, mode: 'insensitive' } : undefined, hotels: hotelId ? { some: { hotelId, active: true } } : undefined }, include: { hotels: { where: hotelId ? { hotelId } : undefined, include: { hotel: { select: { id: true, name: true } } } }, _count: { select: { reservations: true } } }, orderBy: { name: 'asc' } }); return rows.map((row) => this.view(row)); }
  async detail(userId: string, id: string) { const scope = await this.scope(userId); const row = await this.p.corporateAccount.findUnique({ where: { id }, include: { hotels: { where: scope.hotelId ? { hotelId: scope.hotelId } : undefined, include: { hotel: { select: { id: true, name: true } } } }, rateAgreements: { where: scope.hotelId ? { hotelId: scope.hotelId } : undefined, include: { hotel: { select: { id: true, name: true } }, roomType: { select: { id: true, name: true } }, ratePlan: { select: { id: true, name: true } } } } } }); if (!row || (scope.hotelId && !row.hotels.length)) throw new NotFoundException('Corporate account not found.'); return this.view(row); }
  async create(userId: string, body: CorporateCreateDto) { await this.scope(userId, true); const row = await this.p.corporateAccount.create({ data: { ...body, name: body.name.trim(), legalName: body.legalName?.trim(), creditLimit: body.creditLimit, creditDays: body.creditDays } }); await this.audit.log({ actorUserId: userId, action: 'CORPORATE_ACCOUNT_CREATED', entityType: 'CorporateAccount', entityId: row.id, after: { name: row.name } }); return this.view(row); }
  async update(userId: string, id: string, body: CorporateCreateDto) { const scope = await this.scope(userId, true); const current = await this.p.corporateAccount.findUnique({ where: { id }, include: { hotels: true } }); if (!current || (scope.hotelId && !current.hotels.some((link) => link.hotelId === scope.hotelId))) throw new NotFoundException('Corporate account not found.'); const row = await this.p.corporateAccount.update({ where: { id }, data: { ...body, name: body.name?.trim(), creditLimit: body.creditLimit, creditDays: body.creditDays } }); await this.audit.log({ actorUserId: userId, action: 'CORPORATE_ACCOUNT_UPDATED', entityType: 'CorporateAccount', entityId: id, after: { fields: Object.keys(body) } }); return this.view(row); }
  async linkHotel(userId: string, accountId: string, body: CorporateLinkHotelDto) { const scope = await this.scope(userId, true); await assertActorCanManageHotel(this.p, userId, body.hotelId); const account = await this.p.corporateAccount.findUnique({ where: { id: accountId } }); if (!account) throw new NotFoundException('Corporate account not found.'); const row = await this.p.corporateAccountHotel.upsert({ where: { corporateAccountId_hotelId: { corporateAccountId: accountId, hotelId: body.hotelId } }, create: { corporateAccountId: accountId, hotelId: body.hotelId, accountCode: body.accountCode, creditLimitOverride: body.creditLimitOverride, creditDaysOverride: body.creditDaysOverride, active: body.active ?? true }, update: { accountCode: body.accountCode, creditLimitOverride: body.creditLimitOverride, creditDaysOverride: body.creditDaysOverride, active: body.active ?? true } }); await this.audit.log({ actorUserId: userId, action: 'CORPORATE_HOTEL_LINKED', entityType: 'CorporateAccountHotel', entityId: `${accountId}:${body.hotelId}`, after: { corporateAccountId: accountId, hotelId: body.hotelId, active: row.active } }); return row; }
  async createRate(userId: string, accountId: string, body: CorporateRateDto) { await this.accountForHotel(userId, accountId, body.hotelId); if (body.validTo < body.validFrom) throw new BadRequestException('validTo must be on or after validFrom.'); if (body.pricingType === CorporatePricingType.FIXED && body.fixedRate === undefined) throw new BadRequestException('fixedRate is required for a fixed agreement.'); if (body.pricingType === CorporatePricingType.DISCOUNT_PERCENT && body.discountPercent === undefined) throw new BadRequestException('discountPercent is required for a discount agreement.'); const targets = await this.p.ratePlan.findFirst({ where: { id: body.ratePlanId, roomTypeId: body.roomTypeId, roomType: { hotelId: body.hotelId } }, select: { id: true } }); if (!targets) throw new BadRequestException('Rate plan and room type do not belong to the selected hotel.'); const row = await this.p.corporateRateAgreement.create({ data: { corporateAccountId: accountId, hotelId: body.hotelId, roomTypeId: body.roomTypeId, ratePlanId: body.ratePlanId, validFrom: new Date(body.validFrom), validTo: new Date(body.validTo), pricingType: body.pricingType, fixedRate: body.fixedRate, discountPercent: body.discountPercent, active: body.active ?? true }, include: { hotel: { select: { id: true, name: true } }, roomType: { select: { id: true, name: true } }, ratePlan: { select: { id: true, name: true } } } }); await this.audit.log({ actorUserId: userId, action: 'CORPORATE_RATE_CREATED', entityType: 'CorporateRateAgreement', entityId: row.id, after: { corporateAccountId: accountId, hotelId: body.hotelId, pricingType: body.pricingType } }); return this.view(row); }
  async updateRate(userId: string, id: string, body: CorporateRateDto) { const current = await this.p.corporateRateAgreement.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Corporate rate agreement not found.'); await this.accountForHotel(userId, current.corporateAccountId, current.hotelId); const row = await this.p.corporateRateAgreement.update({ where: { id }, data: { validFrom: body.validFrom ? new Date(body.validFrom) : undefined, validTo: body.validTo ? new Date(body.validTo) : undefined, pricingType: body.pricingType, fixedRate: body.fixedRate, discountPercent: body.discountPercent, active: body.active } }); await this.audit.log({ actorUserId: userId, action: 'CORPORATE_RATE_UPDATED', entityType: 'CorporateRateAgreement', entityId: id, after: { fields: Object.keys(body) } }); return row; }
  async receivables(userId: string, id: string) { const scope = await this.scope(userId); const account = await this.p.corporateAccount.findUnique({ where: { id }, include: { hotels: { select: { hotelId: true } } } }); if (!account || (scope.hotelId && !account.hotels.some((link) => link.hotelId === scope.hotelId))) throw new NotFoundException('Corporate account not found.'); const rows = await this.p.reservation.findMany({ where: { corporateAccountId: id, hotelId: scope.hotelId ?? undefined }, include: { hotel: { select: { id: true, name: true } }, payments: { where: { verified: true }, select: { amount: true } }, settlement: { select: { balanceAmount: true } } }, orderBy: { checkOut: 'desc' } }); return rows.map((row) => { const payments = row.payments.reduce((sum, payment) => sum + amount(payment.amount), 0); const gross = amount(row.totalAmount); return { reference: row.reference, guestName: row.guestName, hotel: row.hotel, checkoutDate: row.checkOut, gross, payments, outstanding: Math.max(gross - payments, 0), settlementBalance: row.settlement ? amount(row.settlement.balanceAmount) : null }; }); }
  async applyCorporateRate(userId: string, accountId: string, hotelId: string, roomTypeId: string, ratePlanId: string, stayDate: string, publicPrePromoRate: number) { await this.accountForHotel(userId, accountId, hotelId); const agreement = await this.p.corporateRateAgreement.findFirst({ where: { corporateAccountId: accountId, hotelId, roomTypeId, ratePlanId, active: true, validFrom: { lte: new Date(stayDate) }, validTo: { gte: new Date(stayDate) } } }); if (!agreement) return { agreement: null, resolvedRate: publicPrePromoRate, precedence: 'Public pre-promo rate' }; const resolvedRate = agreement.pricingType === CorporatePricingType.FIXED ? amount(agreement.fixedRate) : Number((publicPrePromoRate * (1 - amount(agreement.discountPercent) / 100)).toFixed(2)); return { agreement: { id: agreement.id, pricingType: agreement.pricingType }, resolvedRate, precedence: agreement.pricingType === CorporatePricingType.FIXED ? 'Corporate fixed rate overrides public Season/Yield rate; promotion eligibility remains explicit.' : 'Corporate discount applies to resolved public pre-promo rate; promotion eligibility remains explicit.' }; }
}
