import { CorporatePricingType } from '@prisma/client';
import { IsBoolean, IsDateString, IsEnum, IsNumber, IsOptional, IsString, Max, Min, MinLength } from 'class-validator';

export class CorporateListQueryDto { @IsOptional() @IsString() hotelId?: string; @IsOptional() @IsString() search?: string; @IsOptional() active?: boolean; }
export class CorporateCreateDto {
  @IsString() @MinLength(2) name!: string; @IsOptional() @IsString() legalName?: string; @IsOptional() @IsString() gstin?: string; @IsOptional() @IsString() pan?: string; @IsOptional() @IsString() billingAddress?: string; @IsOptional() @IsString() city?: string; @IsOptional() @IsString() state?: string; @IsOptional() @IsString() country?: string; @IsOptional() @IsString() postalCode?: string; @IsOptional() @IsString() contactPerson?: string; @IsOptional() @IsString() email?: string; @IsOptional() @IsString() mobile?: string; @IsOptional() @IsNumber() @Min(0) creditLimit?: number; @IsOptional() @IsNumber() @Min(0) creditDays?: number; @IsOptional() active?: boolean;
}
export class CorporateUpdateDto {
  @IsOptional() @IsString() @MinLength(2) name?: string; @IsOptional() @IsString() legalName?: string; @IsOptional() @IsString() gstin?: string; @IsOptional() @IsString() pan?: string; @IsOptional() @IsString() billingAddress?: string; @IsOptional() @IsString() city?: string; @IsOptional() @IsString() state?: string; @IsOptional() @IsString() country?: string; @IsOptional() @IsString() postalCode?: string; @IsOptional() @IsString() contactPerson?: string; @IsOptional() @IsString() email?: string; @IsOptional() @IsString() mobile?: string; @IsOptional() @IsNumber() @Min(0) creditLimit?: number; @IsOptional() @IsNumber() @Min(0) creditDays?: number; @IsOptional() active?: boolean;
}
export class CorporateLinkHotelDto { @IsString() hotelId!: string; @IsOptional() @IsString() accountCode?: string; @IsOptional() @IsNumber() @Min(0) creditLimitOverride?: number; @IsOptional() @IsNumber() @Min(0) creditDaysOverride?: number; @IsOptional() active?: boolean; }
export class CorporateRateDto { @IsString() hotelId!: string; @IsString() roomTypeId!: string; @IsString() ratePlanId!: string; @IsDateString() validFrom!: string; @IsDateString() validTo!: string; @IsEnum(CorporatePricingType) pricingType!: CorporatePricingType; @IsOptional() @IsNumber() @Min(0) fixedRate?: number; @IsOptional() @IsNumber() @Min(0) @Max(100) discountPercent?: number; @IsOptional() active?: boolean; }
export class CorporateRateUpdateDto { @IsOptional() @IsString() hotelId?: string; @IsOptional() @IsString() roomTypeId?: string; @IsOptional() @IsString() ratePlanId?: string; @IsOptional() @IsDateString() validFrom?: string; @IsOptional() @IsDateString() validTo?: string; @IsOptional() @IsEnum(CorporatePricingType) pricingType?: CorporatePricingType; @IsOptional() @IsNumber() @Min(0) fixedRate?: number | null; @IsOptional() @IsNumber() @Min(0) @Max(100) discountPercent?: number | null; @IsOptional() @IsBoolean() active?: boolean; }
export class CorporateReceivableQueryDto { @IsOptional() @IsBoolean() onlyOutstanding?: boolean; }
