'use client';

import { FormEvent, useEffect, useState } from 'react';
import { AdminLayout } from '../../../components/Shell';
import { apiRequest } from '../../../lib/api';

type Agent = { id: string; name: string; email: string; role: string; active: boolean; assignedRatePlans: { ratePlan: { id: string; name: string; code: string } }[] };
const blank = { name: '', email: '', password: '' };

export default function AgentsPage() {
  const [agents, setAgents] = useState<Agent[]>([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState<Agent | null>(null); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function load() { try { setAgents(await apiRequest<Agent[]>('/users/agents')); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load agents'); } }
  useEffect(() => { void load(); }, []);
  function create() { setEditing(null); setForm(blank); setOpen(true); setError(''); setMessage(''); }
  function edit(agent: Agent) { setEditing(agent); setForm({ name: agent.name, email: agent.email, password: '' }); setOpen(true); setError(''); setMessage(''); }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { if (editing) { await apiRequest(`/users/agents/${editing.id}`, { method: 'PATCH', body: JSON.stringify({ name: form.name, active: editing.active }) }); setMessage('Agent updated.'); } else { await apiRequest('/users/agents', { method: 'POST', body: JSON.stringify(form) }); setMessage('Agent created.'); } setOpen(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save agent'); } finally { setBusy(false); } }
  async function toggle(agent: Agent) { setBusy(true); try { await apiRequest(`/users/agents/${agent.id}`, { method: 'PATCH', body: JSON.stringify({ active: !agent.active }) }); setMessage(agent.active ? 'Agent deactivated.' : 'Agent activated.'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not update agent'); } finally { setBusy(false); } }
  return <AdminLayout title="Agents"><section className="masterPanel"><div className="listToolbar"><div><span>Partner access</span><h2>Agents</h2><p>Create and manage agent accounts before assigning their available rate plans.</p></div><button className="btn" type="button" onClick={create}>+ Add Agent</button></div>{error && <p className="error" role="alert">{error}</p>}{message && <p className="notice" role="status">{message}</p>}{open && <form className="formCard masterForm" onSubmit={submit}><div className="rangeSectionHeader"><h2>{editing ? 'Edit agent' : 'Add agent'}</h2><button className="smallBtn" type="button" onClick={() => setOpen(false)}>Close</button></div><label>Agency / agent name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} disabled={Boolean(editing)} required /></label>{!editing && <label>Password<input type="password" minLength={12} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="At least 12 characters" required /></label>}<button className="btn" disabled={busy}>{busy ? 'Saving...' : editing ? 'Save changes' : 'Create agent'}</button></form>}<section className="panel"><div className="tableScroll"><table><thead><tr><th>Agent</th><th>Email</th><th>Assigned rate plans</th><th>Status</th><th>Actions</th></tr></thead><tbody>{agents.map((agent) => <tr key={agent.id}><td><b>{agent.name}</b></td><td>{agent.email}</td><td>{agent.assignedRatePlans.length ? agent.assignedRatePlans.map((item) => <span className="tag" key={item.ratePlan.id}>{item.ratePlan.code}</span>) : <span className="mutedText">None</span>}</td><td><span className={`status ${agent.active ? 'ok' : 'err'}`}>{agent.active ? 'Active' : 'Inactive'}</span></td><td><div className="rowActions"><button className="smallBtn" type="button" onClick={() => edit(agent)}>Edit</button><button className="smallBtn secondary" type="button" disabled={busy} onClick={() => void toggle(agent)}>{agent.active ? 'Deactivate' : 'Activate'}</button></div></td></tr>)}</tbody></table></div></section></section></AdminLayout>;
}
