'use client';

import { useEffect, useMemo, useState } from 'react';
import { AdminLayout } from '../../../components/Shell';
import { apiRequest } from '../../../lib/api';

type Plan = { id: string; code: string; name: string; mealPlan: string; active: boolean; roomType: { name: string; hotel: { name: string; city: string } } };
type Agent = { id: string; name: string; email: string; active: boolean; assignedRatePlans: { ratePlan: { id: string } }[] };

export default function AgentMappingsPage() {
  const [agents, setAgents] = useState<Agent[]>([]); const [plans, setPlans] = useState<Plan[]>([]); const [agentId, setAgentId] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const agent = useMemo(() => agents.find((item) => item.id === agentId), [agents, agentId]);
  useEffect(() => { Promise.all([apiRequest<Agent[]>('/users/agents'), apiRequest<Plan[]>('/hotels/rate-plans')]).then(([loadedAgents, loadedPlans]) => { setAgents(loadedAgents); setPlans(loadedPlans.filter((item) => item.active)); if (loadedAgents[0]) { setAgentId(loadedAgents[0].id); setSelected(loadedAgents[0].assignedRatePlans.map((item) => item.ratePlan.id)); } }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load mappings')).finally(() => setLoading(false)); }, []);
  function chooseAgent(id: string) { setAgentId(id); const next = agents.find((item) => item.id === id); setSelected(next?.assignedRatePlans.map((item) => item.ratePlan.id) ?? []); setMessage(''); }
  function togglePlan(id: string) { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  async function save() { if (!agentId) return; setBusy(true); setError(''); setMessage(''); try { await apiRequest(`/users/agents/${agentId}/rate-plans`, { method: 'PUT', body: JSON.stringify({ ratePlanIds: selected }) }); setAgents((current) => current.map((item) => item.id === agentId ? { ...item, assignedRatePlans: selected.map((id) => ({ ratePlan: { id } })) } : item)); setMessage(`Saved ${selected.length} rate plan${selected.length === 1 ? '' : 's'} for ${agent?.name}.`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save mapping'); } finally { setBusy(false); } }
  return <AdminLayout title="Agent Rate-Plan Mapping"><section className="masterPanel"><div className="listToolbar"><div><span>Access control</span><h2>Assign rate plans to agents</h2><p>Each agent can see and use only the selected active rate plans when creating bookings.</p></div></div>{error && <p className="error" role="alert">{error}</p>}{message && <p className="notice" role="status">{message}</p>}{loading ? <p className="loading">Loading mappings...</p> : <><label>Choose agent<select value={agentId} onChange={(e) => chooseAgent(e.target.value)}><option value="">Select agent</option>{agents.map((item) => <option key={item.id} value={item.id}>{item.name} - {item.email}</option>)}</select></label>{agentId && <><div className="mappingHeader"><h3>{agent?.name}</h3><span>{selected.length} selected</span></div><div className="mappingGrid">{plans.map((plan) => <label className={`mappingCard ${selected.includes(plan.id) ? 'selected' : ''}`} key={plan.id}><input type="checkbox" checked={selected.includes(plan.id)} onChange={() => togglePlan(plan.id)} /><span className="mappingCode">{plan.code}</span><span><b>{plan.name}</b><small>{plan.roomType.hotel.name} / {plan.roomType.name} · {plan.mealPlan}</small></span></label>)}</div><button className="btn" type="button" disabled={busy} onClick={() => void save()}>{busy ? 'Saving...' : 'Save assignments'}</button></>}</>}</section></AdminLayout>;
}
