'use client';
import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { AdminLayout } from '../../../components/Shell';
import { apiFileBlob, apiRequest } from '../../../lib/api';

type Hotel = { id: string; name: string; code: string; city: string };
type ImportResult = { rowsReceived: number; rowsValid: number; rowsInvalid: number; rowsImported: number; rowsUpdated: number; errors: { row: number; field: string; message: string }[] };

export default function BaseRateImportPage() {
  const searchParams = useSearchParams();
  const [hotels, setHotels] = useState<Hotel[]>([]); const [hotelId, setHotelId] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { apiRequest<Hotel[]>('/hotels').then((items) => { setHotels(items); const requested = searchParams.get('hotelId'); setHotelId(items.some((item) => item.id === requested) ? requested! : items[0]?.id ?? ''); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load hotels')); }, [searchParams]);
  async function download() { if (!hotelId) return; try { const blob = await apiFileBlob(`/hotels/${hotelId}/rates/import-template.xlsx`); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'rainwood-base-rate-template.xlsx'; link.click(); URL.revokeObjectURL(url); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not download template'); } }
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !hotelId) return; setBusy(true); setError(''); setMessage(''); try { const form = new FormData(); form.append('file', file); const result = await apiRequest<ImportResult>(`/hotels/${hotelId}/rates/import`, { method: 'POST', body: form }); if (result.errors.length) setError(`Received ${result.rowsReceived} row(s): ${result.rowsInvalid} invalid. No rows were saved.\n${result.errors.map((item) => `Row ${item.row} — ${item.field} — ${item.message}`).join('\n')}`); else setMessage(`Received ${result.rowsReceived}; valid ${result.rowsValid}; imported ${result.rowsImported}; updated ${result.rowsUpdated}.`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not import rates'); } finally { setBusy(false); event.target.value = ''; } }
  return <AdminLayout title="Base Rate Excel Import"><section className="masterPanel"><div className="listToolbar"><div><span>Rate management</span><h2>Base Rate Excel Import</h2><p>Import normal hotel rates into RateDay. Agent contract rates remain separate.</p></div></div>{error && <pre className="error" role="alert">{error}</pre>}{message && <p className="notice" role="status">{message}</p>}<section className="formCard masterForm"><label>Hotel<select value={hotelId} onChange={(event) => setHotelId(event.target.value)}><option value="">Select hotel</option>{hotels.map((hotel) => <option key={hotel.id} value={hotel.id}>{hotel.name} ({hotel.code})</option>)}</select></label><div className="rowActions"><button className="smallBtn" type="button" onClick={() => void download()} disabled={!hotelId || busy}>Download Sample Excel</button><label className="smallBtn">{busy ? 'Importing...' : 'Choose Excel to Import'}<input type="file" accept=".xlsx,.xlsm" hidden onChange={(event) => void upload(event)} disabled={!hotelId || busy} /></label></div><p className="mutedText">The full workbook is validated first. Errors show row, field, and message, and no rows are saved when validation fails.</p></section></section></AdminLayout>;
}
