import { StaffDepartment, ServiceItemType, LostFoundType, LostFoundStatus, GuestServiceOrderStatus } from '@prisma/client';
import { Type } from 'class-transformer';
import { IsArray, IsBoolean, IsDateString, IsEnum, IsNumber, IsOptional, IsString, Max, MaxLength, Min, MinLength, ValidateNested } from 'class-validator';

export class ServiceItemQueryDto { @IsOptional() @IsString() hotelId?: string; @IsOptional() @IsEnum(ServiceItemType) type?: ServiceItemType; @IsOptional() @IsBoolean() active?: boolean; }
export class ServiceItemCreateDto { @IsString() hotelId!: string; @IsEnum(ServiceItemType) type!: ServiceItemType; @IsOptional() @IsString() @MaxLength(40) code?: string; @IsString() @MinLength(2) @MaxLength(120) name!: string; @IsOptional() @IsString() @MaxLength(500) description?: string; @Type(() => Number) @IsNumber() @Min(0) unitPrice!: number; @Type(() => Number) @IsNumber() @Min(0) @Max(100) taxRate = 0; @IsOptional() @IsBoolean() active?: boolean; }
export class ServiceItemUpdateDto { @IsOptional() @IsEnum(ServiceItemType) type?: ServiceItemType; @IsOptional() @IsString() @MaxLength(40) code?: string | null; @IsOptional() @IsString() @MinLength(2) @MaxLength(120) name?: string; @IsOptional() @IsString() @MaxLength(500) description?: string | null; @IsOptional() @IsNumber() @Min(0) unitPrice?: number; @IsOptional() @IsNumber() @Min(0) @Max(100) taxRate?: number; @IsOptional() @IsBoolean() active?: boolean; }
export class ServiceOrderLineDto { @IsString() serviceItemId!: string; @Type(() => Number) @IsNumber() @Min(0.01) quantity!: number; }
export class ServiceOrderCreateDto { @IsEnum(StaffDepartment) department!: StaffDepartment; @IsOptional() @IsString() roomAssignmentId?: string; @IsString() @MinLength(8) @MaxLength(120) idempotencyKey!: string; @IsArray() @ValidateNested({ each: true }) @Type(() => ServiceOrderLineDto) lines!: ServiceOrderLineDto[]; }
export class ServiceOrderQueryDto { @IsOptional() @IsString() hotelId?: string; @IsOptional() @IsEnum(StaffDepartment) department?: StaffDepartment; @IsOptional() @IsEnum(GuestServiceOrderStatus) status?: GuestServiceOrderStatus; @IsOptional() @IsDateString() from?: string; @IsOptional() @IsDateString() to?: string; }
export class LostFoundCreateDto { @IsString() hotelId!: string; @IsEnum(LostFoundType) type!: LostFoundType; @IsString() @MinLength(2) itemCategory!: string; @IsString() @MinLength(2) description!: string; @IsOptional() @IsString() roomId?: string; @IsOptional() @IsString() reservationId?: string; @IsOptional() @IsString() guestProfileId?: string; @IsOptional() @IsString() assignedToId?: string; @IsOptional() @IsString() locationFound?: string; @IsOptional() @IsDateString() foundAt?: string; @IsOptional() @IsString() notes?: string; }
export class LostFoundQueryDto { @IsOptional() @IsString() hotelId?: string; @IsOptional() @IsEnum(LostFoundType) type?: LostFoundType; @IsOptional() @IsEnum(LostFoundStatus) status?: LostFoundStatus; @IsOptional() @IsString() roomId?: string; @IsOptional() @IsDateString() from?: string; @IsOptional() @IsDateString() to?: string; @IsOptional() @IsString() search?: string; }
export class LostFoundMatchDto { @IsOptional() @IsString() reservationId?: string; @IsOptional() @IsString() guestProfileId?: string; @IsOptional() @IsString() assignedToId?: string; @IsOptional() @IsString() notes?: string; }
export class LostFoundReturnDto { @IsString() @MinLength(2) claimantName!: string; @IsString() @MinLength(5) claimantMobile!: string; @IsOptional() @IsString() notes?: string; }
export class LostFoundDisposeDto { @IsString() @MinLength(2) disposalReason!: string; }
