import { BadRequestException, ForbiddenException } from '@nestjs/common';
import { LostFoundStatus, LostFoundType, ServiceItemType, StaffDepartment, UserRole } from '@prisma/client';
import { GuestServicesService } from './guest-services.service';

describe('GuestServicesService', () => {
  const actor = (role: UserRole, hotelId: string | null = 'hotel-a', department: StaffDepartment | null = null) => ({ id: 'user-1', role, staffHotelId: hotelId, staffDepartment: department, staffHotel: hotelId ? { id: hotelId, active: true } : null });
  const p: any = { user: { findUnique: jest.fn() }, hotel: { findUnique: jest.fn() }, room: { findUnique: jest.fn() }, reservation: { findUnique: jest.fn() }, documentSequence: { upsert: jest.fn() }, serviceItem: { findMany: jest.fn(), create: jest.fn(), findUnique: jest.fn(), update: jest.fn() }, guestServiceOrder: { findUnique: jest.fn(), create: jest.fn(), update: jest.fn(), findMany: jest.fn() }, reservationFolioCharge: { create: jest.fn() }, lostFoundItem: { create: jest.fn(), findUnique: jest.fn(), findMany: jest.fn(), update: jest.fn() }, $transaction: jest.fn() };
  const audit = { log: jest.fn() } as any;
  let service: GuestServicesService;
  beforeEach(() => { jest.clearAllMocks(); service = new GuestServicesService(p, audit); p.user.findUnique.mockResolvedValue(actor(UserRole.ADMIN)); p.hotel.findUnique.mockResolvedValue({ id: 'hotel-a', active: true }); p.documentSequence.upsert.mockResolvedValue({ lastNumber: 1 }); });

  it('reports a found item with a hotel-local reference and audit event', async () => { p.lostFoundItem.create.mockImplementation(async ({ data }: any) => ({ ...data, id: 'lf-1', hotel: { id: 'hotel-a', name: 'A' }, room: null, reservation: null, guestProfile: null, reportedBy: { id: 'user-1', name: 'Admin' }, assignedTo: null, returnedBy: null })); const result = await service.reportLost('user-1', { hotelId: 'hotel-a', type: LostFoundType.FOUND, itemCategory: 'Watch', description: 'Silver watch' }); expect(result.reference).toBe('FND-2026-000001'); expect(audit.log).toHaveBeenCalledWith(expect.objectContaining({ action: 'LOST_FOUND_REPORTED' })); });
  it('rejects a room from another hotel', async () => { p.room.findUnique.mockResolvedValue({ id: 'room-b', hotelId: 'hotel-b' }); await expect(service.reportLost('user-1', { hotelId: 'hotel-a', type: LostFoundType.FOUND, itemCategory: 'Watch', description: 'Silver watch', roomId: 'room-b' })).rejects.toBeInstanceOf(BadRequestException); });
  it('allows service staff to report only their assigned hotel', async () => { p.user.findUnique.mockResolvedValue(actor(UserRole.SERVICE_STAFF, 'hotel-a', StaffDepartment.HOUSEKEEPING)); p.lostFoundItem.create.mockImplementation(async ({ data }: any) => ({ ...data, id: 'lf-1', hotel: { id: 'hotel-a', name: 'A' }, room: null, reservation: null, guestProfile: null, reportedBy: { id: 'user-1', name: 'Staff' }, assignedTo: null, returnedBy: null })); await expect(service.reportLost('user-1', { hotelId: 'hotel-b', type: LostFoundType.FOUND, itemCategory: 'Watch', description: 'Silver watch' })).rejects.toBeInstanceOf(ForbiddenException); const result = await service.reportLost('user-1', { hotelId: 'hotel-a', type: LostFoundType.FOUND, itemCategory: 'Watch', description: 'Silver watch' }); expect(result.hotel.id).toBe('hotel-a'); });
  it('posts structured service pricing through one folio charge', async () => { p.user.findUnique.mockResolvedValue(actor(UserRole.SERVICE_STAFF, 'hotel-a', StaffDepartment.FOOD_BEVERAGE)); const tx: any = { guestServiceOrder: { findUnique: jest.fn().mockResolvedValue(null), create: jest.fn(), update: jest.fn() }, reservation: { findUnique: jest.fn().mockResolvedValue({ id: 'res-1', reference: 'RW-1', hotelId: 'hotel-a', stayStatus: 'CHECKED_IN', hotel: { id: 'hotel-a', timezoneName: 'Asia/Kolkata' }, roomAssignments: [{ id: 'assign-1', room: { id: 'room-1', roomNumber: '203' } }] }) }, serviceItem: { findMany: jest.fn().mockResolvedValue([{ id: 'item-1', type: ServiceItemType.FOOD, name: 'Dinner', unitPrice: 450, taxRate: 10 }]) }, documentSequence: { upsert: jest.fn().mockResolvedValue({ lastNumber: 1 }) }, reservationFolioCharge: { create: jest.fn().mockResolvedValue({ id: 'charge-1' }) }, auditLog: { create: jest.fn() } }; const order: any = { id: 'order-1', orderNo: 'FNB-2026-000001', department: StaffDepartment.FOOD_BEVERAGE, subtotalAmount: 450, taxAmount: 45, totalAmount: 495, lines: [{ serviceItem: { id: 'item-1', name: 'Dinner', type: ServiceItemType.FOOD }, quantity: 1, unitPriceSnapshot: 450, taxRateSnapshot: 10, taxableAmount: 450, taxAmount: 45, lineTotal: 495 }], roomAssignment: { room: { id: 'room-1', roomNumber: '203' } } }; tx.guestServiceOrder.create.mockResolvedValue(order); tx.guestServiceOrder.update.mockResolvedValue(order); p.$transaction.mockImplementation(async (callback: any) => callback(tx)); const result = await service.createOrder('user-1', 'RW-1', { department: StaffDepartment.FOOD_BEVERAGE, idempotencyKey: 'synthetic-order-1', lines: [{ serviceItemId: 'item-1', quantity: 1 }] }); expect(result.totalAmount).toBe(495); expect(tx.reservationFolioCharge.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ totalAmount: 495, category: 'FOOD_AND_BEVERAGE' }) })); });
  it('rejects housekeeping from posting non-laundry items', async () => { p.user.findUnique.mockResolvedValue(actor(UserRole.SERVICE_STAFF, 'hotel-a', StaffDepartment.HOUSEKEEPING)); const tx: any = { guestServiceOrder: { findUnique: jest.fn().mockResolvedValue(null) }, reservation: { findUnique: jest.fn().mockResolvedValue({ id: 'res-1', reference: 'RW-1', hotelId: 'hotel-a', stayStatus: 'CHECKED_IN', hotel: { timezoneName: 'Asia/Kolkata' }, roomAssignments: [{ id: 'assign-1', room: { id: 'room-1' } }] }) }, serviceItem: { findMany: jest.fn().mockResolvedValue([{ id: 'item-1', type: ServiceItemType.FOOD, name: 'Dinner', unitPrice: 450, taxRate: 0 }]) } }; p.$transaction.mockImplementation(async (callback: any) => callback(tx)); await expect(service.createOrder('user-1', 'RW-1', { department: StaffDepartment.HOUSEKEEPING, idempotencyKey: 'synthetic-order-2', lines: [{ serviceItemId: 'item-1', quantity: 1 }] })).rejects.toBeInstanceOf(ForbiddenException); });
  it('requires management for disposal', async () => { p.user.findUnique.mockResolvedValue(actor(UserRole.RESERVATION)); await expect(service.disposeLost('user-1', 'lf-1', { disposalReason: 'No claim' })).rejects.toBeInstanceOf(ForbiddenException); });
  it('keeps the lifecycle explicit for return', async () => { p.user.findUnique.mockResolvedValue(actor(UserRole.ADMIN)); p.lostFoundItem.findUnique.mockResolvedValue({ id: 'lf-1', hotelId: 'hotel-a', status: LostFoundStatus.OPEN }); await expect(service.returnLost('user-1', 'lf-1', { claimantName: 'Guest', claimantMobile: '9999999999' })).rejects.toThrow('Only matched items can be returned.'); });
});
